/* Auto-generated by weights_export_c_source. DO NOT EDIT. */
#include <stddef.h>

size_t demo_weights_count(void) {
    return 4U;
}

const float* demo_weights_data(void) {
    static const float data[4] = {
    2.500000000e-01f, -5.000000000e-01f, 1.000000000e+00f, 2.000000000e+00f
    };
    return data;
}

int demo_weights_copy(float* out, size_t out_capacity) {
    size_t i = 0U;
    const float* src = demo_weights_data();
    if (out == NULL || out_capacity < 4U) {
        return -1;
    }
    for (i = 0U; i < 4U; ++i) {
        out[i] = src[i];
    }
    return 0;
}
