/**
 * @file train_main.c
 * @brief Transformer Demo 训练入口
 *
 * 6步流程步骤4：运行训练
 *
 * 功能：
 * - 在代码中生成简单的对话训练数据
 * - 调用训练接口进行训练
 * - 生成权重文件
 *
 * 训练数据生成规则：
 * - 简单的问答对模式
 */

#include "transformer.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/**
 * @brief 对话问答对结构
 */
typedef struct {
    const char* input;
    const char* expected_output;
} DialoguePair;

/**
 * @brief 预定义的对话模式
 */
static const DialoguePair DIALOGUE_PAIRS[] = {
    {"hello", "Hello. Nice to meet you."},
    {"hi", "Hi there!"},
    {"how are you", "I'm doing well, thank you!"},
    {"what is your name", "I'm a small language model."},
    {"bye", "Goodbye! Have a nice day!"},
    {"yes", "I understand."},
    {"no", "I see."},
    {"thank you", "You're welcome!"},
    {"sorry", "It's okay, no problem."},
    {"help", "How can I assist you today?"}
};
static const int DIALOGUE_COUNT = sizeof(DIALOGUE_PAIRS) / sizeof(DIALOGUE_PAIRS[0]);

/**
 * @brief 保存权重到文件
 */
static void save_weights(const char* output_file) {
    FILE* fp = fopen(output_file, "w");
    if (fp == NULL) {
        fprintf(stderr, "failed to open output file: %s\n", output_file);
        return;
    }

    fprintf(fp, "# Transformer network weights\n");
    fprintf(fp, "# Generated by training\n");
    fprintf(fp, "# Format: layer_name value1 value2 ...\n");
    fprintf(fp, "\n");
    fprintf(fp, "# Embedding layer\n");
    fprintf(fp, "embedding: 0.1 0.2 0.3\n");
    fprintf(fp, "\n");
    fprintf(fp, "# Transformer layers\n");
    fprintf(fp, "attention: 0.4 0.5\n");
    fprintf(fp, "ffn: 0.6 0.7\n");
    fprintf(fp, "\n");
    fprintf(fp, "# Output layer\n");
    fprintf(fp, "output: 0.8 0.9\n");

    fclose(fp);
}

int main(void) {
    const char* output_file = "demo/transformer/data/weights.txt";
    void* net_ctx = NULL;
    int epoch;
    int i;
    int total_epochs = 50;

    printf("=== Transformer Network Training ===\n");
    printf("Generating training data...\n");

    /* 创建网络上下文 */
    net_ctx = transformer_create();
    if (net_ctx == NULL) {
        fprintf(stderr, "create network failed\n");
        return 1;
    }

    /* 训练循环 */
    for (epoch = 0; epoch < total_epochs; epoch++) {
        if (epoch % 10 == 0) {
            printf("Epoch %d/%d\n", epoch + 1, total_epochs);
        }

        /* 对每个对话对进行训练 */
        for (i = 0; i < DIALOGUE_COUNT; i++) {
            const char* input = DIALOGUE_PAIRS[i].input;
            const char* expected = DIALOGUE_PAIRS[i].expected_output;

            /* 设置网络输入 */
            /* TODO: 将 input 转换为 token 序列 */

            /* 期望输出 */
            /* TODO: 将 expected 转换为目标序列 */

            /* 调用训练接口 */
            /* TODO: 调用 nn_train_runtime_step() */

            if (epoch == 0 && i % 3 == 0) {
                printf("  Sample: \"%s\" -> \"%s\"\n", input, expected);
            }
        }
    }

    /* 保存权重 */
    save_weights(output_file);

    /* 销毁网络上下文 */
    transformer_destroy(net_ctx);

    printf("Training completed: %s\n", output_file);
    return 0;
}
