/**
 * @file action_nn_c.js
 * @brief JavaScript binding layer for action_nn_c WebAssembly module
 * 
 * This is a placeholder file. The actual JavaScript glue code will be
 * generated by Emscripten during the build process.
 * 
 * After building with:
 *   ./scripts/build_wasm.sh
 * 
 * The generated files in dist/ will include:
 *   - action_nn_c.js (Emscripten glue code)
 *   - action_nn_c.wasm (WebAssembly binary)
 * 
 * This file exists to provide documentation and type hints for IDEs.
 */

// Example usage (after build):
// 
// import ActionNnC from './dist/action_nn_c.js';
// 
// async function init() {
//     const Module = await ActionNnC();
//     
//     // Get version
//     const version = Module.action_c_wasm_get_version_string();
//     console.log('Version:', version);
//     
//     // Get supported networks
//     const count = Module.action_c_wasm_get_network_type_count();
//     for (let i = 0; i < count; i++) {
//         const name = Module.action_c_wasm_get_network_type_name(i);
//         console.log('Network:', name);
//     }
//     
//     // Create inference context (requires proper config)
//     const configPtr = Module._malloc(configSize);
//     Module.HEAPU8.set(configBytes, configPtr);
//     const ctx = Module.action_c_wasm_infer_create(configPtr, configSize);
//     
//     // Run inference
//     const inputPtr = Module._malloc(inputSize);
//     const outputPtr = Module._malloc(outputSize);
//     Module.HEAPF32.set(inputData, inputPtr / 4);
//     Module.action_c_wasm_infer_run(ctx, inputPtr, inputSize, outputPtr, outputSize);
//     const outputData = Module.HEAPF32.slice(outputPtr / 4, outputPtr / 4 + outputLength);
//     
//     // Cleanup
//     Module.action_c_wasm_infer_destroy(ctx);
//     Module._free(inputPtr);
//     Module._free(outputPtr);
//     Module._free(configPtr);
// }

console.warn(
    'This is a placeholder file. ' +
    'Please build the WebAssembly module using ./scripts/build_wasm.sh ' +
    'and use the generated files in the dist/ directory.'
);

export default function ActionNnC(config) {
    throw new Error(
        'Wasm module not built. Please run ./scripts/build_wasm.sh first.'
    );
}
