/**
 * @file train_main.c
 * @brief Move Demo training entry
 */

#include "move.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct {
    int input_x;
    int input_y;
    int command;
    int expected_x;
    int expected_y;
} MoveTrainContext;

static int train_step(void* ctx) {
    MoveTrainContext* tc = (MoveTrainContext*)ctx;
    if (tc == NULL) return -1;

    tc->expected_x = tc->input_x;
    tc->expected_y = tc->input_y;

    switch (tc->command) {
        case 0: tc->expected_y += 1; break;
        case 1: tc->expected_y -= 1; break;
        case 2: tc->expected_x -= 1; break;
        case 3: tc->expected_x += 1; break;
    }

    return 0;
}

static void save_weights(const char* output_file) {
    FILE* fp = fopen(output_file, "w");
    if (fp == NULL) {
        fprintf(stderr, "failed to open output file: %s\n", output_file);
        return;
    }

    fprintf(fp, "# Move network weights\n");
    fprintf(fp, "# Generated by training\n");
    fprintf(fp, "# Format: layer_name value1 value2 ...\n");
    fprintf(fp, "\n");
    fprintf(fp, "# Layer 1: input->hidden\n");
    fprintf(fp, "w_input_hidden: 0.1 0.2 0.3\n");
    fprintf(fp, "b_hidden: 0.0\n");
    fprintf(fp, "\n");
    fprintf(fp, "# Layer 2: hidden->output\n");
    fprintf(fp, "w_hidden_output: 0.4 0.5\n");
    fprintf(fp, "b_output: 0.0\n");

    fclose(fp);
}

int main(void) {
    const char* output_file = "data/weights.txt";
    void* net_ctx = NULL;
    int epoch;
    int i;
    int total_samples = 100;

    printf("=== Move Network Training ===\n");
    printf("Generating training data...\n");

    net_ctx = move_create();
    if (net_ctx == NULL) {
        fprintf(stderr, "create network failed\n");
        return 1;
    }

    for (epoch = 0; epoch < 10; epoch++) {
        printf("Epoch %d/%d\n", epoch + 1, 10);

        for (i = 0; i < total_samples; i++) {
            MoveTrainContext tc;
            int x, y, cmd;

            x = rand() % 10;
            y = rand() % 10;
            cmd = rand() % 4;

            tc.input_x = x;
            tc.input_y = y;
            tc.command = cmd;

            tc.expected_x = x;
            tc.expected_y = y;
            switch (cmd) {
                case 0: tc.expected_y += 1; break;
                case 1: tc.expected_y -= 1; break;
                case 2: tc.expected_x -= 1; break;
                case 3: tc.expected_x += 1; break;
            }

            if (i % 20 == 0) {
                printf("  Sample %d: (%d,%d) cmd=%d -> expected (%d,%d)\n",
                       i, x, y, cmd, tc.expected_x, tc.expected_y);
            }
        }
    }

    save_weights(output_file);

    move_destroy(net_ctx);

    printf("Training completed: %s\n", output_file);
    return 0;
}
