#if defined(_WIN32) && !defined(_CRT_SECURE_NO_WARNINGS)
#define _CRT_SECURE_NO_WARNINGS
#endif

#include "../include/weights_io.h"

#include <ctype.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/**
 * @brief 权重二进制文件头。
 */
typedef struct WeightsBinaryHeader {
    unsigned char magic[4];
    uint32_t version;
    uint32_t count;
} WeightsBinaryHeader;

/**
 * @brief 校验符号名是否为合法 C 标识符。
 *
 * @param symbol 符号名
 * @return int 1=合法，0=非法
 */
static int weights_is_valid_symbol(const char* symbol) {
    size_t i = 0U;
    if (symbol == NULL || symbol[0] == '\0') {
        return 0;
    }
    if (!(isalpha((unsigned char)symbol[0]) || symbol[0] == '_')) {
        return 0;
    }
    for (i = 1U; symbol[i] != '\0'; ++i) {
        if (!(isalnum((unsigned char)symbol[i]) || symbol[i] == '_')) {
            return 0;
        }
    }
    return 1;
}

/**
 * @brief 保存 float 权重数组为二进制文件。
 *
 * 二进制布局：
 * - Header: magic("WGTB"), version(1), count(uint32)
 * - Data: float[count]
 *
 * @param file_path  输出文件路径
 * @param weights    权重数据指针
 * @param count      权重元素数量
 * @return int       WeightsIoStatus
 */
int weights_save_binary(const char* file_path, const float* weights, size_t count) {
    FILE* fp = NULL;
    WeightsBinaryHeader header;
    if (file_path == NULL || weights == NULL || count == 0U || count > (size_t)UINT32_MAX) {
        return WEIGHTS_IO_STATUS_INVALID_ARGUMENT;
    }
    fp = fopen(file_path, "wb");
    if (fp == NULL) {
        return WEIGHTS_IO_STATUS_IO_ERROR;
    }
    header.magic[0] = (unsigned char)'W';
    header.magic[1] = (unsigned char)'G';
    header.magic[2] = (unsigned char)'T';
    header.magic[3] = (unsigned char)'B';
    header.version = (uint32_t)1U;
    header.count = (uint32_t)count;

    if (fwrite(&header, sizeof(header), 1U, fp) != 1U) {
        fclose(fp);
        return WEIGHTS_IO_STATUS_IO_ERROR;
    }
    if (fwrite(weights, sizeof(float), count, fp) != count) {
        fclose(fp);
        return WEIGHTS_IO_STATUS_IO_ERROR;
    }
    fclose(fp);
    return WEIGHTS_IO_STATUS_OK;
}

/**
 * @brief 从二进制文件加载 float 权重数组。
 *
 * @param file_path   输入文件路径
 * @param out_weights 输出权重指针（调用方使用 free 释放）
 * @param out_count   输出权重数量
 * @return int        WeightsIoStatus
 */
int weights_load_binary(const char* file_path, float** out_weights, size_t* out_count) {
    FILE* fp = NULL;
    WeightsBinaryHeader header;
    float* weights = NULL;
    if (file_path == NULL || out_weights == NULL || out_count == NULL) {
        return WEIGHTS_IO_STATUS_INVALID_ARGUMENT;
    }
    *out_weights = NULL;
    *out_count = 0U;
    fp = fopen(file_path, "rb");
    if (fp == NULL) {
        return WEIGHTS_IO_STATUS_IO_ERROR;
    }
    if (fread(&header, sizeof(header), 1U, fp) != 1U) {
        fclose(fp);
        return WEIGHTS_IO_STATUS_IO_ERROR;
    }
    if (header.magic[0] != (unsigned char)'W' ||
        header.magic[1] != (unsigned char)'G' ||
        header.magic[2] != (unsigned char)'T' ||
        header.magic[3] != (unsigned char)'B' ||
        header.version != (uint32_t)1U) {
        fclose(fp);
        return WEIGHTS_IO_STATUS_FORMAT_ERROR;
    }
    if (header.count == 0U) {
        fclose(fp);
        return WEIGHTS_IO_STATUS_FORMAT_ERROR;
    }
    weights = (float*)malloc((size_t)header.count * sizeof(float));
    if (weights == NULL) {
        fclose(fp);
        return WEIGHTS_IO_STATUS_OOM;
    }
    if (fread(weights, sizeof(float), (size_t)header.count, fp) != (size_t)header.count) {
        free(weights);
        fclose(fp);
        return WEIGHTS_IO_STATUS_IO_ERROR;
    }
    fclose(fp);
    *out_weights = weights;
    *out_count = (size_t)header.count;
    return WEIGHTS_IO_STATUS_OK;
}

/**
 * @brief 将权重导出为可直接编译的 C 源码模块（函数接口）。
 *
 * 关键保护点：
 * - 强制校验符号名，避免生成非法 C 代码。
 * - 每行固定输出数量，保持源码可读性与差异审查稳定性。
 *
 * @param file_path  输出 C 源文件路径
 * @param symbol     导出符号前缀（必须是合法 C 标识符）
 * @param weights    权重数据指针
 * @param count      权重元素数量
 * @return int       WeightsIoStatus
 */
int weights_export_c_source(const char* file_path,
                            const char* symbol,
                            const float* weights,
                            size_t count) {
    FILE* fp = NULL;
    size_t i = 0U;
    if (file_path == NULL || symbol == NULL || weights == NULL || count == 0U) {
        return WEIGHTS_IO_STATUS_INVALID_ARGUMENT;
    }
    if (!weights_is_valid_symbol(symbol)) {
        return WEIGHTS_IO_STATUS_INVALID_ARGUMENT;
    }
    fp = fopen(file_path, "w");
    if (fp == NULL) {
        return WEIGHTS_IO_STATUS_IO_ERROR;
    }

    fprintf(fp, "/* Auto-generated by weights_export_c_source. DO NOT EDIT. */\n");
    fprintf(fp, "#include <stddef.h>\n\n");
    fprintf(fp, "size_t %s_count(void) {\n", symbol);
    fprintf(fp, "    return %zuU;\n", count);
    fprintf(fp, "}\n\n");
    fprintf(fp, "const float* %s_data(void) {\n", symbol);
    fprintf(fp, "    static const float data[%zu] = {\n", count);
    for (i = 0U; i < count; ++i) {
        if ((i % 8U) == 0U) {
            fprintf(fp, "    ");
        }
        fprintf(fp, "%.9ef%s", (double)weights[i], (i + 1U < count) ? ", " : "");
        if (((i % 8U) == 7U) || (i + 1U == count)) {
            fprintf(fp, "\n");
        }
    }
    fprintf(fp, "    };\n");
    fprintf(fp, "    return data;\n");
    fprintf(fp, "}\n\n");
    fprintf(fp, "int %s_copy(float* out, size_t out_capacity) {\n", symbol);
    fprintf(fp, "    size_t i = 0U;\n");
    fprintf(fp, "    const float* src = %s_data();\n", symbol);
    fprintf(fp, "    if (out == NULL || out_capacity < %zuU) {\n", count);
    fprintf(fp, "        return -1;\n");
    fprintf(fp, "    }\n");
    fprintf(fp, "    for (i = 0U; i < %zuU; ++i) {\n", count);
    fprintf(fp, "        out[i] = src[i];\n");
    fprintf(fp, "    }\n");
    fprintf(fp, "    return 0;\n");
    fprintf(fp, "}\n");
    fclose(fp);
    return WEIGHTS_IO_STATUS_OK;
}

int weights_export_c_function_network(const char* file_path,
                                      const char* symbol,
                                      const float* weights,
                                      size_t vocab_size,
                                      size_t max_token_count,
                                      size_t state_dim,
                                      size_t output_dim,
                                      const int* activations) {
    FILE* fp = NULL;
    size_t j = 0U;
    size_t i = 0U;
    size_t t = 0U;
    const size_t token_weight_count = vocab_size * output_dim;
    const size_t state_weight_count = state_dim * output_dim;
    if (file_path == NULL || symbol == NULL || weights == NULL || activations == NULL ||
        vocab_size == 0U || max_token_count == 0U || state_dim == 0U || output_dim == 0U) {
        return WEIGHTS_IO_STATUS_INVALID_ARGUMENT;
    }
    if (!weights_is_valid_symbol(symbol)) {
        return WEIGHTS_IO_STATUS_INVALID_ARGUMENT;
    }
    fp = fopen(file_path, "w");
    if (fp == NULL) {
        return WEIGHTS_IO_STATUS_IO_ERROR;
    }

    fprintf(fp, "#include <stddef.h>\n");
    fprintf(fp, "#include <math.h>\n\n");
    fprintf(fp, "static float %s_sigmoid(float x) {\n", symbol);
    fprintf(fp, "    return 1.0f / (1.0f + expf(-x));\n");
    fprintf(fp, "}\n\n");
    fprintf(fp, "size_t %s_vocab_size(void) { return %zuU; }\n", symbol, vocab_size);
    fprintf(fp, "size_t %s_state_dim(void) { return %zuU; }\n", symbol, state_dim);
    fprintf(fp, "size_t %s_output_dim(void) { return %zuU; }\n", symbol, output_dim);
    fprintf(fp, "size_t %s_token_slots(void) { return %zuU; }\n\n", symbol, max_token_count);

    for (t = 0U; t < max_token_count; ++t) {
        for (i = 0U; i < vocab_size; ++i) {
            fprintf(fp, "static float %s_in_token_%zu_%zu(const float* x) {\n", symbol, t, i);
            fprintf(fp, "    return x[%zuU];\n", t * vocab_size + i);
            fprintf(fp, "}\n\n");
        }
    }
    for (i = 0U; i < state_dim; ++i) {
        fprintf(fp, "static float %s_in_state_%zu(const float* s) {\n", symbol, i);
        fprintf(fp, "    return s[%zuU];\n", i);
        fprintf(fp, "}\n\n");
    }

    for (j = 0U; j < output_dim; ++j) {
        fprintf(fp, "static float %s_neuron_%zu(const float* x, const float* s, float inv_token_count) {\n", symbol, j);
        fprintf(fp, "    float z = %.9ef;\n",
                (double)weights[token_weight_count + state_weight_count + j]);
        for (t = 0U; t < max_token_count; ++t) {
            for (i = 0U; i < vocab_size; ++i) {
                const size_t widx = i * output_dim + j;
                fprintf(fp, "    z += %s_in_token_%zu_%zu(x) * %.9ef * inv_token_count;\n",
                        symbol, t, i, (double)weights[widx]);
            }
        }
        for (i = 0U; i < state_dim; ++i) {
            const size_t swidx = token_weight_count + i * output_dim + j;
            fprintf(fp, "    z += %s_in_state_%zu(s) * %.9ef;\n", symbol, i, (double)weights[swidx]);
        }
        fprintf(fp, "    return z;\n");
        fprintf(fp, "}\n\n");
    }

    fprintf(fp, "void %s_forward(const float* token_onehot, size_t token_count, const float* state, float* out) {\n", symbol);
    fprintf(fp, "    float inv_token_count = (token_count > 0U) ? (1.0f / (float)token_count) : 0.0f;\n");
    for (j = 0U; j < output_dim; ++j) {
        fprintf(fp, "    {\n");
        fprintf(fp, "        float z = %s_neuron_%zu(token_onehot, state, inv_token_count);\n", symbol, j);
        if (activations[j] == 0) {
            fprintf(fp, "        out[%zuU] = %s_sigmoid(z);\n", j, symbol);
        } else {
            fprintf(fp, "        out[%zuU] = tanhf(z);\n", j);
        }
        fprintf(fp, "    }\n");
    }
    fprintf(fp, "}\n");
    fclose(fp);
    return WEIGHTS_IO_STATUS_OK;
}
