set(ACTION_C_DEMO_COMMON_DIR "${CMAKE_CURRENT_LIST_DIR}")
get_filename_component(ACTION_C_ROOT "${ACTION_C_DEMO_COMMON_DIR}/.." ABSOLUTE)
include(CMakeParseArguments)

function(action_c_enable_network_types)
    set(options)
    set(oneValueArgs)
    set(multiValueArgs TYPES)
    cmake_parse_arguments(ACTION_C_ENABLE "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    set(ACTION_C_ENABLE_NN_MLP OFF CACHE BOOL "Enable the built-in MLP network type" FORCE)
    set(ACTION_C_ENABLE_NN_TRANSFORMER OFF CACHE BOOL "Enable the built-in transformer network type" FORCE)
    set(ACTION_C_ENABLE_NN_CNN OFF CACHE BOOL "Enable the built-in CNN network type" FORCE)
    set(ACTION_C_ENABLE_NN_CNN_DUAL_POOL OFF CACHE BOOL "Enable the built-in dual-pool CNN network type" FORCE)
    set(ACTION_C_ENABLE_NN_RNN OFF CACHE BOOL "Enable the built-in RNN network type" FORCE)
    set(ACTION_C_ENABLE_NN_GNN OFF CACHE BOOL "Enable the built-in GNN network type" FORCE)

    foreach(ACTION_C_TYPE IN LISTS ACTION_C_ENABLE_TYPES)
        if(ACTION_C_TYPE STREQUAL "mlp")
            set(ACTION_C_ENABLE_NN_MLP ON CACHE BOOL "Enable the built-in MLP network type" FORCE)
        elseif(ACTION_C_TYPE STREQUAL "transformer")
            set(ACTION_C_ENABLE_NN_TRANSFORMER ON CACHE BOOL "Enable the built-in transformer network type" FORCE)
        elseif(ACTION_C_TYPE STREQUAL "cnn")
            set(ACTION_C_ENABLE_NN_CNN ON CACHE BOOL "Enable the built-in CNN network type" FORCE)
        elseif(ACTION_C_TYPE STREQUAL "cnn_dual_pool")
            set(ACTION_C_ENABLE_NN_CNN_DUAL_POOL ON CACHE BOOL "Enable the built-in dual-pool CNN network type" FORCE)
        elseif(ACTION_C_TYPE STREQUAL "rnn")
            set(ACTION_C_ENABLE_NN_RNN ON CACHE BOOL "Enable the built-in RNN network type" FORCE)
        elseif(ACTION_C_TYPE STREQUAL "gnn")
            set(ACTION_C_ENABLE_NN_GNN ON CACHE BOOL "Enable the built-in GNN network type" FORCE)
        else()
            message(FATAL_ERROR "Unsupported demo network type: ${ACTION_C_TYPE}")
        endif()
    endforeach()
endfunction()

function(action_c_add_core_subdirectory)
    add_subdirectory("${ACTION_C_ROOT}/src" "${CMAKE_BINARY_DIR}/action_c_src")
endfunction()

function(action_c_get_demo_generated_dir OUT_VAR)
    get_filename_component(_generated_dir "${CMAKE_BINARY_DIR}/../data" ABSOLUTE)
    set(${OUT_VAR} "${_generated_dir}" PARENT_SCOPE)
endfunction()

function(action_c_add_demo_clean_target DEMO_NAME)
    add_custom_target(${DEMO_NAME}_clean
        COMMAND ${CMAKE_COMMAND} -E rm -rf "${CMAKE_CURRENT_SOURCE_DIR}/../build/${DEMO_NAME}"
        COMMENT "Clean generated and built files for ${DEMO_NAME} demo"
    )
endfunction()

function(action_c_apply_strict_warnings TARGET_NAME)
    if(MSVC)
        target_compile_options(${TARGET_NAME} PRIVATE /W4 /WX)
    else()
        target_compile_options(${TARGET_NAME} PRIVATE -Wall -Wextra -Wpedantic -Werror)
    endif()
endfunction()
