# --- Single source of truth: version number ---
# This file is include()'d by CMakeLists.txt that need the version.
#
# Provides:
#   ACTION_C_VERSION{_MAJOR,_MINOR,_PATCH,_STRING}
#   action_c_generate_version_header(OUT_DIR)  -- writes action_c_version.h

set(ACTION_C_VERSION_MAJOR 1)
set(ACTION_C_VERSION_MINOR 0)
set(ACTION_C_VERSION_PATCH 0)
set(ACTION_C_VERSION "${ACTION_C_VERSION_MAJOR}.${ACTION_C_VERSION_MINOR}.${ACTION_C_VERSION_PATCH}")
set(ACTION_C_VERSION_STRING "${ACTION_C_VERSION}")

function(action_c_generate_version_header OUT_DIR)
    set(VERSION_HEADER "${OUT_DIR}/action_c_version.h")
    file(WRITE "${VERSION_HEADER}"
        "/* Auto-generated by cmake/version.cmake. DO NOT EDIT. */\n"
        "#ifndef ACTION_C_VERSION_H\n"
        "#define ACTION_C_VERSION_H\n"
        "#define ACTION_C_VERSION_MAJOR ${ACTION_C_VERSION_MAJOR}\n"
        "#define ACTION_C_VERSION_MINOR ${ACTION_C_VERSION_MINOR}\n"
        "#define ACTION_C_VERSION_PATCH ${ACTION_C_VERSION_PATCH}\n"
        "#define ACTION_C_VERSION_STRING \"${ACTION_C_VERSION}\"\n"
        "#endif\n"
    )
endfunction()
