/**
 * @file prof_codegen.c
 * @brief Code generation implementation
 */

#include "prof_codegen.h"
#include "prof_error.h"

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#ifdef _WIN32
#include <direct.h>
#define MKDIR(path) _mkdir(path)
#else
#define MKDIR(path) mkdir(path, 0755)
#endif

#define ABI_VERSION 1

/**
 * @brief Write content to file at given path
 */
static ProfStatus write_file(const char* path, const char* content) {
    FILE* fp;

    if (path == NULL || content == NULL) {
        return PROF_STATUS_PATH_INVALID;
    }

    fp = fopen(path, "w");
    if (fp == NULL) {
        return PROF_STATUS_IO_FAILED;
    }

    fprintf(fp, "%s", content);
    fclose(fp);

    return PROF_STATUS_OK;
}

/**
 * @brief Ensure parent directories exist for a file path
 */
static ProfStatus ensure_parent_dir(const char* file_path) {
    char path_copy[512];
    char* last_sep;
    int rc;

    if (file_path == NULL) {
        return PROF_STATUS_PATH_INVALID;
    }

    strncpy(path_copy, file_path, sizeof(path_copy) - 1);
    path_copy[sizeof(path_copy) - 1] = '\0';

    last_sep = strrchr(path_copy, '/');
    if (last_sep != NULL) {
        *last_sep = '\0';
        rc = MKDIR(path_copy);
        if (rc != 0) {
            return PROF_STATUS_IO_FAILED;
        }
    }

    return PROF_STATUS_OK;
}

/**
 * @brief Capitalize first character of string
 */
static void capitalize_first(const char* src, char* dest, size_t dest_size) {
    size_t i;
    for (i = 0; i < dest_size - 1 && src[i] != '\0'; i++) {
        if (i == 0) {
            dest[i] = (char)(src[i] >= 'a' && src[i] <= 'z' ?
                src[i] - 'a' + 'A' : src[i]);
        } else {
            dest[i] = src[i];
        }
    }
    dest[i] = '\0';
}

/**
 * @brief Convert activation type to string
 */
static const char* activation_to_string(int activation) {
    switch (activation) {
        case 0: return "none";
        case 1: return "relu";
        case 2: return "sigmoid";
        case 3: return "tanh";
        case 4: return "softmax";
        case 5: return "leaky_relu";
        default: return "relu";
    }
}

void prof_codegen_init(
    ProfCodegenContext* ctx,
    const NN_NetworkDef* network,
    const ProfOutputLayout* output_layout,
    uint64_t network_hash,
    uint64_t layout_hash,
    ProfErrorBuffer* error
) {
    ctx->network = network;
    ctx->output_layout = output_layout;
    ctx->network_hash = network_hash;
    ctx->layout_hash = layout_hash;
    ctx->error = error;
}

ProfStatus prof_codegen_metadata(
    ProfCodegenContext* ctx,
    const char* metadata_path
) {
    FILE* fp;
    const NN_NetworkDef* network;

    if (ctx == NULL || metadata_path == NULL) {
        return PROF_STATUS_INVALID_ARGUMENT;
    }

    network = ctx->network;
    if (network == NULL) {
        return PROF_STATUS_INVALID_ARGUMENT;
    }

    fp = fopen(metadata_path, "w");
    if (fp == NULL) {
        return PROF_STATUS_IO_FAILED;
    }

    fprintf(fp, "/* Network metadata */\n");
    fprintf(fp, "/* This file is auto-generated by profiler */\n\n");
    fprintf(fp, "#ifndef NETWORK_METADATA_H\n");
    fprintf(fp, "#define NETWORK_METADATA_H\n\n");
    fprintf(fp, "#define NETWORK_HASH 0x%016llxULL\n",
        (unsigned long long)ctx->network_hash);
    fprintf(fp, "#define LAYOUT_HASH 0x%016llxULL\n",
        (unsigned long long)ctx->layout_hash);
    fprintf(fp, "#define ABI_VERSION %d\n", ABI_VERSION);
    fprintf(fp, "#define NETWORK_NAME \"%s\"\n", network->network_name);
    fprintf(fp, "#define SUBNET_COUNT %zu\n", network->subnet_count);
    fprintf(fp, "\n#endif\n");

    fclose(fp);

    return PROF_STATUS_OK;
}

ProfStatus prof_codegen_tokenizer(ProfCodegenContext* ctx) {
    ProfStatus st;
    const ProfOutputLayout* layout;
    char content[4096];
    const NN_NetworkDef* network;
    size_t i;
    size_t total_inputs = 0;
    size_t total_outputs = 0;

    if (ctx == NULL) {
        return PROF_STATUS_INVALID_ARGUMENT;
    }

    layout = ctx->output_layout;
    network = ctx->network;

    if (layout == NULL || layout->tokenizer.c_path == NULL) {
        return PROF_STATUS_PATH_INVALID;
    }

    if (network != NULL) {
        for (i = 0; i < network->subnet_count; i++) {
            NNSubnetDef* subnet = network->subnets[i];
            if (subnet != NULL) {
                total_inputs += subnet->input_layer_size;
                total_outputs += subnet->output_layer_size;
            }
        }
    }

    snprintf(content, sizeof(content),
        "/* tokenizer.c - Tokenizer module */\n"
        "/* Auto-generated by profiler */\n\n"
        "#include \"tokenizer.h\"\n"
        "#include <stdlib.h>\n"
        "#include <string.h>\n\n"
        "/* Tokenizer context */\n"
        "typedef struct {\n"
        "    size_t input_count;\n"
        "    size_t output_count;\n"
        "    float* input_buffer;\n"
        "    float* output_buffer;\n"
        "} TokenizerContext;\n\n"
        "void* tokenizer_create(size_t input_count, size_t output_count) {\n"
        "    TokenizerContext* ctx = (TokenizerContext*)malloc(sizeof(TokenizerContext));\n"
        "    if (ctx == NULL) return NULL;\n"
        "    ctx->input_count = input_count;\n"
        "    ctx->output_count = output_count;\n"
        "    ctx->input_buffer = NULL;\n"
        "    ctx->output_buffer = NULL;\n"
        "    return ctx;\n"
        "}\n\n"
        "void tokenizer_destroy(void* ctx) {\n"
        "    if (ctx != NULL) {\n"
        "        TokenizerContext* tc = (TokenizerContext*)ctx;\n"
        "        if (tc->input_buffer != NULL) free(tc->input_buffer);\n"
        "        if (tc->output_buffer != NULL) free(tc->output_buffer);\n"
        "        free(tc);\n"
        "    }\n"
        "}\n\n"
        "int tokenizer_encode(void* ctx, const float* raw_input, size_t raw_count) {\n"
        "    (void)ctx;\n"
        "    (void)raw_input;\n"
        "    (void)raw_count;\n"
        "    return 0;\n"
        "}\n\n"
        "int tokenizer_decode(void* ctx, const float* encoded, size_t encoded_count) {\n"
        "    (void)ctx;\n"
        "    (void)encoded;\n"
        "    (void)encoded_count;\n"
        "    return 0;\n"
        "}\n",
        (size_t)0, (size_t)0);

    st = ensure_parent_dir(layout->tokenizer.c_path);
    if (st != PROF_STATUS_OK) {
        return prof_error_set(ctx->error, st,
            "Failed to create directory for tokenizer.c");
    }

    st = write_file(layout->tokenizer.c_path, content);
    if (st != PROF_STATUS_OK) {
        return prof_error_set(ctx->error, st,
            "Failed to write tokenizer.c");
    }

    if (layout->tokenizer.h_path != NULL) {
        const char* header_content =
            "/* tokenizer.h - Tokenizer interface */\n"
            "/* Auto-generated by profiler */\n\n"
            "#ifndef TOKENIZER_H\n"
            "#define TOKENIZER_H\n\n"
            "#include <stddef.h>\n\n"
            "void* tokenizer_create(size_t input_count, size_t output_count);\n"
            "void tokenizer_destroy(void* ctx);\n"
            "int tokenizer_encode(void* ctx, const float* raw_input, size_t raw_count);\n"
            "int tokenizer_decode(void* ctx, const float* encoded, size_t encoded_count);\n\n"
            "#endif\n";

        st = ensure_parent_dir(layout->tokenizer.h_path);
        if (st == PROF_STATUS_OK) {
            write_file(layout->tokenizer.h_path, header_content);
        }
    }

    return PROF_STATUS_OK;
}

ProfStatus prof_codegen_network_init(ProfCodegenContext* ctx) {
    ProfStatus st;
    const ProfOutputLayout* layout;
    const NN_NetworkDef* network;
    char content[8192];
    size_t i;
    size_t pos = 0;
    size_t remaining = sizeof(content);
    int written;

    if (ctx == NULL) {
        return PROF_STATUS_INVALID_ARGUMENT;
    }

    layout = ctx->output_layout;
    network = ctx->network;

    if (layout == NULL || layout->network_init.c_path == NULL) {
        return PROF_STATUS_PATH_INVALID;
    }

    written = snprintf(content + pos, remaining,
        "/* network_init.c - Network initialization module */\n"
        "/* Auto-generated by profiler */\n\n"
        "#include \"network_init.h\"\n"
        "#include <stdlib.h>\n"
        "#include <string.h>\n\n");
    pos += written;
    remaining -= written;

    if (network != NULL) {
        for (i = 0; i < network->subnet_count && remaining > 100; i++) {
            NNSubnetDef* subnet = network->subnets[i];
            if (subnet == NULL) continue;

            written = snprintf(content + pos, remaining,
                "/* Subnet: %s, Type: %s */\n"
                "/* Input: %zu, Hidden layers: %zu, Output: %zu */\n",
                subnet->subnet_id,
                subnet->subnet_type,
                (size_t)subnet->input_layer_size,
                (size_t)subnet->hidden_layer_count,
                (size_t)subnet->output_layer_size);
            pos += written;
            remaining -= written;

            if (subnet->hidden_layer_count > 0 && subnet->hidden_layer_sizes != NULL) {
                size_t j;
                for (j = 0; j < subnet->hidden_layer_count && remaining > 100; j++) {
                    written = snprintf(content + pos, remaining,
                        "/* Hidden layer %zu: %zu nodes */\n",
                        (size_t)j, (size_t)subnet->hidden_layer_sizes[j]);
                    pos += written;
                    remaining -= written;
                }
            }
        }
    }

    written = snprintf(content + pos, remaining,
        "\nvoid* network_init_create(void) {\n"
        "    return NULL;\n"
        "}\n\n"
        "void network_init_destroy(void* ctx) {\n"
        "    (void)ctx;\n"
        "}\n\n"
        "int network_init_weights(void* ctx, void* network_ctx) {\n"
        "    (void)ctx;\n"
        "    (void)network_ctx;\n"
        "    return 0;\n"
        "}\n");

    st = ensure_parent_dir(layout->network_init.c_path);
    if (st != PROF_STATUS_OK) {
        return prof_error_set(ctx->error, st,
            "Failed to create directory for network_init.c");
    }

    st = write_file(layout->network_init.c_path, content);
    if (st != PROF_STATUS_OK) {
        return prof_error_set(ctx->error, st,
            "Failed to write network_init.c");
    }

    if (layout->network_init.h_path != NULL) {
        const char* header_content =
            "/* network_init.h - Network initialization interface */\n"
            "/* Auto-generated by profiler */\n\n"
            "#ifndef NETWORK_INIT_H\n"
            "#define NETWORK_INIT_H\n\n"
            "#include <stddef.h>\n\n"
            "void* network_init_create(void);\n"
            "void network_init_destroy(void* ctx);\n"
            "int network_init_weights(void* ctx, void* network_ctx);\n\n"
            "#endif\n";

        st = ensure_parent_dir(layout->network_init.h_path);
        if (st == PROF_STATUS_OK) {
            write_file(layout->network_init.h_path, header_content);
        }
    }

    return PROF_STATUS_OK;
}

ProfStatus prof_codegen_weights_load(ProfCodegenContext* ctx) {
    ProfStatus st;
    const ProfOutputLayout* layout;
    const NN_NetworkDef* network;
    char content[4096];

    if (ctx == NULL) {
        return PROF_STATUS_INVALID_ARGUMENT;
    }

    layout = ctx->output_layout;
    network = ctx->network;

    if (layout == NULL || layout->weights_load.c_path == NULL) {
        return PROF_STATUS_PATH_INVALID;
    }

    snprintf(content, sizeof(content),
        "/* weights_load.c - Weights loading module */\n"
        "/* Auto-generated by profiler */\n\n"
        "#include \"weights_load.h\"\n"
        "#include \"network_metadata.h\"\n"
        "#include <stdio.h>\n"
        "#include <string.h>\n\n"
        "/* Expected network hash - generated from network definition */\n"
        "static const uint64_t EXPECTED_HASH = 0x%016llxULL;\n"
        "static const uint64_t EXPECTED_LAYOUT_HASH = 0x%016llxULL;\n\n"
        "typedef struct {\n"
        "    uint64_t network_hash;\n"
        "    uint64_t layout_hash;\n"
        "    uint32_t abi_version;\n"
        "} WeightFileHeader;\n\n"
        "int weights_load_from_file(void* ctx, const char* file_path) {\n"
        "    FILE* fp;\n"
        "    WeightFileHeader header;\n"
        "    (void)ctx;\n\n"
        "    if (file_path == NULL) return -1;\n\n"
        "    fp = fopen(file_path, \"rb\");\n"
        "    if (fp == NULL) return -2;\n\n"
        "    if (fread(&header, sizeof(header), 1, fp) != 1) {\n"
        "        fclose(fp);\n"
        "        return -3;\n"
        "    }\n\n"
        "    if (header.network_hash != EXPECTED_HASH) {\n"
        "        fclose(fp);\n"
        "        return -4;\n"
        "    }\n\n"
        "    if (header.layout_hash != EXPECTED_LAYOUT_HASH) {\n"
        "        fclose(fp);\n"
        "        return -5;\n"
        "    }\n\n"
        "    fclose(fp);\n"
        "    return 0;\n"
        "}\n\n"
        "int weights_load_validate(const char* file_path) {\n"
        "    return weights_load_from_file(NULL, file_path);\n"
        "}\n",
        (unsigned long long)ctx->network_hash,
        (unsigned long long)ctx->layout_hash);

    st = ensure_parent_dir(layout->weights_load.c_path);
    if (st != PROF_STATUS_OK) {
        return prof_error_set(ctx->error, st,
            "Failed to create directory for weights_load.c");
    }

    st = write_file(layout->weights_load.c_path, content);
    if (st != PROF_STATUS_OK) {
        return prof_error_set(ctx->error, st,
            "Failed to write weights_load.c");
    }

    if (layout->weights_load.h_path != NULL) {
        const char* header_content =
            "/* weights_load.h - Weights loading interface */\n"
            "/* Auto-generated by profiler */\n\n"
            "#ifndef WEIGHTS_LOAD_H\n"
            "#define WEIGHTS_LOAD_H\n\n"
            "#include <stddef.h>\n"
            "#include <stdint.h>\n\n"
            "int weights_load_from_file(void* ctx, const char* file_path);\n"
            "int weights_load_validate(const char* file_path);\n\n"
            "#endif\n";

        st = ensure_parent_dir(layout->weights_load.h_path);
        if (st == PROF_STATUS_OK) {
            write_file(layout->weights_load.h_path, header_content);
        }
    }

    return PROF_STATUS_OK;
}

ProfStatus prof_codegen_train(ProfCodegenContext* ctx) {
    ProfStatus st;
    const ProfOutputLayout* layout;
    const NN_NetworkDef* network;
    char content[4096];

    if (ctx == NULL) {
        return PROF_STATUS_INVALID_ARGUMENT;
    }

    layout = ctx->output_layout;
    network = ctx->network;

    if (layout == NULL || layout->train.c_path == NULL) {
        return PROF_STATUS_PATH_INVALID;
    }

    snprintf(content, sizeof(content),
        "/* train.c - Training module */\n"
        "/* Auto-generated by profiler */\n"
        "/* Network: %s */\n\n"
        "#include \"train.h\"\n"
        "#include <stdlib.h>\n"
        "#include <string.h>\n\n"
        "typedef struct {\n"
        "    void* network_ctx;\n"
        "    float learning_rate;\n"
        "    int epoch_count;\n"
        "} TrainContext;\n\n"
        "void* train_create(void) {\n"
        "    TrainContext* ctx = (TrainContext*)malloc(sizeof(TrainContext));\n"
        "    if (ctx == NULL) return NULL;\n"
        "    ctx->network_ctx = NULL;\n"
        "    ctx->learning_rate = 0.01f;\n"
        "    ctx->epoch_count = 0;\n"
        "    return ctx;\n"
        "}\n\n"
        "void train_destroy(void* ctx) {\n"
        "    if (ctx != NULL) free(ctx);\n"
        "}\n\n"
        "int train_step(void* ctx, const void* input, const void* target) {\n"
        "    (void)ctx;\n"
        "    (void)input;\n"
        "    (void)target;\n"
        "    return 0;\n"
        "}\n\n"
        "int train_epoch(void* ctx, int epoch) {\n"
        "    (void)ctx;\n"
        "    (void)epoch;\n"
        "    return 0;\n"
        "}\n\n"
        "int train_auto_run(void* ctx, int epochs) {\n"
        "    TrainContext* tc = (TrainContext*)ctx;\n"
        "    int e;\n"
        "    if (tc == NULL) return -1;\n"
        "    for (e = 0; e < epochs; e++) {\n"
        "        train_epoch(ctx, e);\n"
        "    }\n"
        "    tc->epoch_count += epochs;\n"
        "    return 0;\n"
        "}\n",
        network != NULL ? network->network_name : "unknown");

    st = ensure_parent_dir(layout->train.c_path);
    if (st != PROF_STATUS_OK) {
        return prof_error_set(ctx->error, st,
            "Failed to create directory for train.c");
    }

    st = write_file(layout->train.c_path, content);
    if (st != PROF_STATUS_OK) {
        return prof_error_set(ctx->error, st,
            "Failed to write train.c");
    }

    if (layout->train.h_path != NULL) {
        const char* header_content =
            "/* train.h - Training interface */\n"
            "/* Auto-generated by profiler */\n\n"
            "#ifndef TRAIN_H\n"
            "#define TRAIN_H\n\n"
            "#include <stddef.h>\n\n"
            "void* train_create(void);\n"
            "void train_destroy(void* ctx);\n"
            "int train_step(void* ctx, const void* input, const void* target);\n"
            "int train_epoch(void* ctx, int epoch);\n"
            "int train_auto_run(void* ctx, int epochs);\n\n"
            "#endif\n";

        st = ensure_parent_dir(layout->train.h_path);
        if (st == PROF_STATUS_OK) {
            write_file(layout->train.h_path, header_content);
        }
    }

    return PROF_STATUS_OK;
}

ProfStatus prof_codegen_weights_save(ProfCodegenContext* ctx) {
    ProfStatus st;
    const ProfOutputLayout* layout;
    char content[4096];

    if (ctx == NULL) {
        return PROF_STATUS_INVALID_ARGUMENT;
    }

    layout = ctx->output_layout;

    if (layout == NULL || layout->weights_save.c_path == NULL) {
        return PROF_STATUS_PATH_INVALID;
    }

    snprintf(content, sizeof(content),
        "/* weights_save.c - Weights saving module */\n"
        "/* Auto-generated by profiler */\n\n"
        "#include \"weights_save.h\"\n"
        "#include \"network_metadata.h\"\n"
        "#include <stdio.h>\n"
        "#include <string.h>\n\n"
        "typedef struct {\n"
        "    void* network_ctx;\n"
        "} SaveContext;\n\n"
        "typedef struct {\n"
        "    uint64_t network_hash;\n"
        "    uint64_t layout_hash;\n"
        "    uint32_t abi_version;\n"
        "} WeightFileHeader;\n\n"
        "void* weights_save_create(void) {\n"
        "    return malloc(sizeof(SaveContext));\n"
        "}\n\n"
        "void weights_save_destroy(void* ctx) {\n"
        "    if (ctx != NULL) free(ctx);\n"
        "}\n\n"
        "int weights_save_to_file(void* ctx, const char* file_path) {\n"
        "    FILE* fp;\n"
        "    WeightFileHeader header;\n"
        "    (void)ctx;\n\n"
        "    if (file_path == NULL) return -1;\n\n"
        "    fp = fopen(file_path, \"wb\");\n"
        "    if (fp == NULL) return -2;\n\n"
        "    header.network_hash = NETWORK_HASH;\n"
        "    header.layout_hash = LAYOUT_HASH;\n"
        "    header.abi_version = ABI_VERSION;\n\n"
        "    if (fwrite(&header, sizeof(header), 1, fp) != 1) {\n"
        "        fclose(fp);\n"
        "        return -3;\n"
        "    }\n\n"
        "    fclose(fp);\n"
        "    return 0;\n"
        "}\n");

    st = ensure_parent_dir(layout->weights_save.c_path);
    if (st != PROF_STATUS_OK) {
        return prof_error_set(ctx->error, st,
            "Failed to create directory for weights_save.c");
    }

    st = write_file(layout->weights_save.c_path, content);
    if (st != PROF_STATUS_OK) {
        return prof_error_set(ctx->error, st,
            "Failed to write weights_save.c");
    }

    if (layout->weights_save.h_path != NULL) {
        const char* header_content =
            "/* weights_save.h - Weights saving interface */\n"
            "/* Auto-generated by profiler */\n\n"
            "#ifndef WEIGHTS_SAVE_H\n"
            "#define WEIGHTS_SAVE_H\n\n"
            "#include <stddef.h>\n\n"
            "void* weights_save_create(void);\n"
            "void weights_save_destroy(void* ctx);\n"
            "int weights_save_to_file(void* ctx, const char* file_path);\n\n"
            "#endif\n";

        st = ensure_parent_dir(layout->weights_save.h_path);
        if (st == PROF_STATUS_OK) {
            write_file(layout->weights_save.h_path, header_content);
        }
    }

    return PROF_STATUS_OK;
}

ProfStatus prof_codegen_infer(ProfCodegenContext* ctx) {
    ProfStatus st;
    const ProfOutputLayout* layout;
    const NN_NetworkDef* network;
    char content[4096];
    size_t i;

    if (ctx == NULL) {
        return PROF_STATUS_INVALID_ARGUMENT;
    }

    layout = ctx->output_layout;
    network = ctx->network;

    if (layout == NULL || layout->infer.c_path == NULL) {
        return PROF_STATUS_PATH_INVALID;
    }

    snprintf(content, sizeof(content),
        "/* infer.c - Inference module */\n"
        "/* Auto-generated by profiler */\n"
        "/* Network: %s */\n\n"
        "#include \"infer.h\"\n"
        "#include <stdlib.h>\n"
        "#include <string.h>\n\n",
        network != NULL ? network->network_name : "unknown");

    if (network != NULL) {
        for (i = 0; i < network->subnet_count; i++) {
            NNSubnetDef* subnet = network->subnets[i];
            char type_cap[64];
            if (subnet == NULL) continue;

            capitalize_first(subnet->subnet_type, type_cap, sizeof(type_cap));
        }
    }

    strcat(content,
        "typedef struct {\n"
        "    void* network_ctx;\n"
        "} InferContext;\n\n"
        "void* infer_create(void) {\n"
        "    InferContext* ctx = (InferContext*)malloc(sizeof(InferContext));\n"
        "    if (ctx == NULL) return NULL;\n"
        "    ctx->network_ctx = NULL;\n"
        "    return ctx;\n"
        "}\n\n"
        "void infer_destroy(void* ctx) {\n"
        "    if (ctx != NULL) free(ctx);\n"
        "}\n\n"
        "int infer_step(void* ctx, const void* input, void* output) {\n"
        "    (void)ctx;\n"
        "    (void)input;\n"
        "    (void)output;\n"
        "    return 0;\n"
        "}\n\n"
        "int infer_auto_run(void* ctx, const void* input, void* output) {\n"
        "    return infer_step(ctx, input, output);\n"
        "}\n");

    st = ensure_parent_dir(layout->infer.c_path);
    if (st != PROF_STATUS_OK) {
        return prof_error_set(ctx->error, st,
            "Failed to create directory for infer.c");
    }

    st = write_file(layout->infer.c_path, content);
    if (st != PROF_STATUS_OK) {
        return prof_error_set(ctx->error, st,
            "Failed to write infer.c");
    }

    if (layout->infer.h_path != NULL) {
        const char* header_content =
            "/* infer.h - Inference interface */\n"
            "/* Auto-generated by profiler */\n\n"
            "#ifndef INFER_H\n"
            "#define INFER_H\n\n"
            "#include <stddef.h>\n\n"
            "void* infer_create(void);\n"
            "void infer_destroy(void* ctx);\n"
            "int infer_step(void* ctx, const void* input, void* output);\n"
            "int infer_auto_run(void* ctx, const void* input, void* output);\n\n"
            "#endif\n";

        st = ensure_parent_dir(layout->infer.h_path);
        if (st == PROF_STATUS_OK) {
            write_file(layout->infer.h_path, header_content);
        }
    }

    return PROF_STATUS_OK;
}

ProfStatus prof_codegen_generate_all(ProfCodegenContext* ctx) {
    ProfStatus st;

    if (ctx == NULL || ctx->network == NULL) {
        return PROF_STATUS_INVALID_ARGUMENT;
    }

    st = prof_codegen_metadata(ctx, ctx->output_layout->metadata_path);
    if (st != PROF_STATUS_OK) return st;

    st = prof_codegen_tokenizer(ctx);
    if (st != PROF_STATUS_OK) return st;

    st = prof_codegen_network_init(ctx);
    if (st != PROF_STATUS_OK) return st;

    st = prof_codegen_weights_load(ctx);
    if (st != PROF_STATUS_OK) return st;

    st = prof_codegen_train(ctx);
    if (st != PROF_STATUS_OK) return st;

    st = prof_codegen_weights_save(ctx);
    if (st != PROF_STATUS_OK) return st;

    st = prof_codegen_infer(ctx);
    if (st != PROF_STATUS_OK) return st;

    return PROF_STATUS_OK;
}
