/**
 * @file profiler_types.h
 * @brief Profiler public type definitions
 *
 * Defines all public types for profiler:
 * - Error code enum
 * - Error buffer structure
 * - Module path structure
 * - Output layout structure
 * - Generate request/result structures
 * - Metadata structure
 *
 * Constraints:
 * - All types must comply with C99 standard
 * - Error descriptions use English only
 * - Error buffer recommended capacity >= 256 bytes
 */

#ifndef PROFILER_TYPES_H
#define PROFILER_TYPES_H

#include <stddef.h>
#include <stdint.h>

/**
 * @brief Profiler error code enum
 *
 * Defines possible error status for profiler operations.
 * All error codes must be used with error buffer,
 * outputting to terminal simultaneously.
 */
typedef enum {
    PROF_STATUS_OK = 0,
    PROF_STATUS_INVALID_ARGUMENT = 1,
    PROF_STATUS_VALIDATION_FAILED = 2,
    PROF_STATUS_CYCLE_DETECTED = 3,
    PROF_STATUS_PATH_INVALID = 4,
    PROF_STATUS_IO_FAILED = 5,
    PROF_STATUS_HASH_MISMATCH = 6,
    PROF_STATUS_LAYOUT_MISMATCH = 7,
    PROF_STATUS_INTERNAL_ERROR = 255
} ProfStatus;

/**
 * @brief Error description buffer
 *
 * Used to return detailed error descriptions to caller.
 * Constraints:
 * - buffer must point to writable memory
 * - capacity recommended >= 256 bytes
 * - Error descriptions use English only
 */
typedef struct {
    char* buffer;
    size_t capacity;
} ProfErrorBuffer;

/**
 * @brief Single module output path
 *
 * Defines .c and .h file output paths for single functional module.
 * Supports .c/.h stored in different directories.
 */
typedef struct {
    const char* c_path;
    const char* h_path;
} ProfModulePath;

/**
 * @brief Output layout structure
 *
 * Defines output paths for six functional modules generated by profiler.
 * Each module must specify .c and .h output paths.
 */
typedef struct {
    ProfModulePath tokenizer;
    ProfModulePath network_init;
    ProfModulePath weights_load;
    ProfModulePath train;
    ProfModulePath weights_save;
    ProfModulePath infer;
    const char* metadata_path;
} ProfOutputLayout;

/**
 * @brief Generate request structure
 *
 * Generate request passed from user program to profiler.
 * Contains network definition and output path configuration.
 */
typedef struct {
    const void* network_def;
    ProfOutputLayout output_layout;
    ProfErrorBuffer error;
} ProfGenerateRequest;

/**
 * @brief Generate result structure
 *
 * Generate result returned from profiler to caller.
 */
typedef struct {
    uint64_t network_hash;
    const char* metadata_written_path;
} ProfGenerateResult;

/**
 * @brief Generated metadata structure
 *
 * Shared metadata for training/inference/save/load.
 * Contains network signature hash and layout information.
 */
typedef struct {
    uint64_t network_hash;
    uint64_t layout_hash;
    uint32_t abi_version;
} NNGeneratedMetadata;

/**
 * @brief Convert error code to description string
 *
 * @param status Error code
 * @return Description string for error code
 */
const char* prof_status_to_string(ProfStatus status);

#endif
