/**
 * @file prof_codegen.c
 * @brief Code generation implementation
 */

#include "prof_codegen.h"
#include "prof_error.h"
#include "prof_path.h"

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdarg.h>

#define ABI_VERSION 1

/**
 * @brief Write content to file at given path
 */
static ProfStatus write_file(const char* path, const char* content) {
    FILE* fp;

    if (path == NULL || content == NULL) {
        return PROF_STATUS_PATH_INVALID;
    }

    fp = fopen(path, "w");
    if (fp == NULL) {
        return PROF_STATUS_IO_FAILED;
    }

    fprintf(fp, "%s", content);
    fclose(fp);

    return PROF_STATUS_OK;
}

static int append_format(
    char* buffer,
    size_t buffer_capacity,
    size_t* position,
    const char* format,
    ...
) {
    int written;
    size_t remaining;
    va_list args;

    if (buffer == NULL || position == NULL || format == NULL) {
        return -1;
    }
    if (*position >= buffer_capacity) {
        return -1;
    }

    remaining = buffer_capacity - *position;
    va_start(args, format);
    written = vsnprintf(buffer + *position, remaining, format, args);
    va_end(args);

    if (written < 0 || (size_t)written >= remaining) {
        return -1;
    }

    *position += (size_t)written;
    return 0;
}

static int append_type_config_blob(
    char* buffer,
    size_t buffer_capacity,
    size_t* position,
    const char* symbol_name,
    const unsigned char* data,
    size_t data_size
) {
    size_t index;

    if (buffer == NULL || position == NULL || symbol_name == NULL) {
        return -1;
    }

    if (append_format(
            buffer,
            buffer_capacity,
            position,
            "static const unsigned char %s[] = {\n",
            symbol_name) != 0) {
        return -1;
    }

    for (index = 0U; index < data_size; ++index) {
        if ((index % 12U) == 0U) {
            if (append_format(buffer, buffer_capacity, position, "    ") != 0) {
                return -1;
            }
        }
        if (append_format(
                buffer,
                buffer_capacity,
                position,
                "0x%02X%s",
                (unsigned int)data[index],
                (index + 1U < data_size) ? ", " : "") != 0) {
            return -1;
        }
        if ((index % 12U) == 11U || (index + 1U) == data_size) {
            if (append_format(buffer, buffer_capacity, position, "\n") != 0) {
                return -1;
            }
        }
    }

    if (append_format(buffer, buffer_capacity, position, "};\n\n") != 0) {
        return -1;
    }

    return 0;
}

void prof_codegen_init(
    ProfCodegenContext* ctx,
    const NN_NetworkDef* network,
    const ProfOutputLayout* output_layout,
    uint64_t network_hash,
    uint64_t layout_hash,
    ProfErrorBuffer* error
) {
    ctx->network = network;
    ctx->output_layout = output_layout;
    ctx->network_hash = network_hash;
    ctx->layout_hash = layout_hash;
    ctx->error = error;
}

ProfStatus prof_codegen_metadata(
    ProfCodegenContext* ctx,
    const char* metadata_path
) {
    FILE* fp;
    ProfStatus st;
    const NN_NetworkDef* network;

    if (ctx == NULL || metadata_path == NULL) {
        return PROF_STATUS_INVALID_ARGUMENT;
    }

    network = ctx->network;
    if (network == NULL) {
        return PROF_STATUS_INVALID_ARGUMENT;
    }

    st = prof_path_ensure_parent_directory(metadata_path);
    if (st != PROF_STATUS_OK) {
        return prof_error_set(ctx->error, st,
            "Failed to create directory for metadata output");
    }

    fp = fopen(metadata_path, "w");
    if (fp == NULL) {
        return PROF_STATUS_IO_FAILED;
    }

    fprintf(fp, "/* Network metadata */\n");
    fprintf(fp, "/* This file is auto-generated by profiler */\n\n");
    fprintf(fp, "#ifndef NETWORK_METADATA_H\n");
    fprintf(fp, "#define NETWORK_METADATA_H\n\n");
    fprintf(fp, "#define NETWORK_HASH 0x%016llxULL\n",
        (unsigned long long)ctx->network_hash);
    fprintf(fp, "#define LAYOUT_HASH 0x%016llxULL\n",
        (unsigned long long)ctx->layout_hash);
    fprintf(fp, "#define ABI_VERSION %d\n", ABI_VERSION);
    fprintf(fp, "#define NETWORK_NAME \"%s\"\n", network->network_name);
    fprintf(fp, "#define SUBNET_COUNT %zu\n", network->subnet_count);
    fprintf(fp, "\n#endif\n");

    fclose(fp);

    return PROF_STATUS_OK;
}

ProfStatus prof_codegen_tokenizer(ProfCodegenContext* ctx) {
    ProfStatus st;
    const ProfOutputLayout* layout;
    char content[4096];
    const NN_NetworkDef* network;
    size_t i;
    size_t total_inputs = 0;
    size_t total_outputs = 0;

    if (ctx == NULL) {
        return PROF_STATUS_INVALID_ARGUMENT;
    }

    layout = ctx->output_layout;
    network = ctx->network;

    if (layout == NULL || layout->tokenizer.c_path == NULL) {
        return PROF_STATUS_PATH_INVALID;
    }

    if (network != NULL) {
        for (i = 0; i < network->subnet_count; i++) {
            NNSubnetDef* subnet = network->subnets[i];
            if (subnet != NULL) {
                total_inputs += subnet->input_layer_size;
                total_outputs += subnet->output_layer_size;
            }
        }
    }

    snprintf(content, sizeof(content),
        "/* tokenizer.c - Tokenizer module */\n"
        "/* Auto-generated by profiler */\n\n"
        "#include \"tokenizer.h\"\n"
        "#include <stdlib.h>\n"
        "#include <string.h>\n\n"
        "/* Tokenizer context */\n"
        "typedef struct {\n"
        "    size_t input_count;\n"
        "    size_t output_count;\n"
        "    float* input_buffer;\n"
        "    float* output_buffer;\n"
        "} TokenizerContext;\n\n"
        "void* tokenizer_create(size_t input_count, size_t output_count) {\n"
        "    TokenizerContext* ctx = (TokenizerContext*)malloc(sizeof(TokenizerContext));\n"
        "    if (ctx == NULL) return NULL;\n"
        "    ctx->input_count = input_count;\n"
        "    ctx->output_count = output_count;\n"
        "    ctx->input_buffer = NULL;\n"
        "    ctx->output_buffer = NULL;\n"
        "    return ctx;\n"
        "}\n\n"
        "void tokenizer_destroy(void* ctx) {\n"
        "    if (ctx != NULL) {\n"
        "        TokenizerContext* tc = (TokenizerContext*)ctx;\n"
        "        if (tc->input_buffer != NULL) free(tc->input_buffer);\n"
        "        if (tc->output_buffer != NULL) free(tc->output_buffer);\n"
        "        free(tc);\n"
        "    }\n"
        "}\n\n"
        "int tokenizer_encode(void* ctx, const float* raw_input, size_t raw_count) {\n"
        "    (void)ctx;\n"
        "    (void)raw_input;\n"
        "    (void)raw_count;\n"
        "    return 0;\n"
        "}\n\n"
        "int tokenizer_decode(void* ctx, const float* encoded, size_t encoded_count) {\n"
        "    (void)ctx;\n"
        "    (void)encoded;\n"
        "    (void)encoded_count;\n"
        "    return 0;\n"
        "}\n");

    st = prof_path_ensure_parent_directory(layout->tokenizer.c_path);
    if (st != PROF_STATUS_OK) {
        return prof_error_set(ctx->error, st,
            "Failed to create directory for tokenizer.c");
    }

    st = write_file(layout->tokenizer.c_path, content);
    if (st != PROF_STATUS_OK) {
        return prof_error_set(ctx->error, st,
            "Failed to write tokenizer.c");
    }

    if (layout->tokenizer.h_path != NULL) {
        const char* header_content =
            "/* tokenizer.h - Tokenizer interface */\n"
            "/* Auto-generated by profiler */\n\n"
            "#ifndef TOKENIZER_H\n"
            "#define TOKENIZER_H\n\n"
            "#include <stddef.h>\n\n"
            "void* tokenizer_create(size_t input_count, size_t output_count);\n"
            "void tokenizer_destroy(void* ctx);\n"
            "int tokenizer_encode(void* ctx, const float* raw_input, size_t raw_count);\n"
            "int tokenizer_decode(void* ctx, const float* encoded, size_t encoded_count);\n\n"
            "#endif\n";

        st = prof_path_ensure_parent_directory(layout->tokenizer.h_path);
        if (st == PROF_STATUS_OK) {
            write_file(layout->tokenizer.h_path, header_content);
        }
    }

    return PROF_STATUS_OK;
}

ProfStatus prof_codegen_network_init(ProfCodegenContext* ctx) {
    ProfStatus st;
    const ProfOutputLayout* layout;
    const NN_NetworkDef* network;
    char content[8192];
    size_t i;
    size_t pos = 0;
    size_t remaining = sizeof(content);
    int written;

    if (ctx == NULL) {
        return PROF_STATUS_INVALID_ARGUMENT;
    }

    layout = ctx->output_layout;
    network = ctx->network;

    if (layout == NULL || layout->network_init.c_path == NULL) {
        return PROF_STATUS_PATH_INVALID;
    }

    written = snprintf(content + pos, remaining,
        "/* network_init.c - Network initialization module */\n"
        "/* Auto-generated by profiler */\n\n"
        "#include \"network_init.h\"\n"
        "#include <stdlib.h>\n"
        "#include <string.h>\n\n");
    pos += written;
    remaining -= written;

    if (network != NULL) {
        for (i = 0; i < network->subnet_count && remaining > 100; i++) {
            NNSubnetDef* subnet = network->subnets[i];
            if (subnet == NULL) continue;

            written = snprintf(content + pos, remaining,
                "/* Subnet: %s, Type: %s */\n"
                "/* Input: %zu, Hidden layers: %zu, Output: %zu */\n",
                subnet->subnet_id,
                subnet->subnet_type,
                (size_t)subnet->input_layer_size,
                (size_t)subnet->hidden_layer_count,
                (size_t)subnet->output_layer_size);
            pos += written;
            remaining -= written;

            if (subnet->hidden_layer_count > 0 && subnet->hidden_layer_sizes != NULL) {
                size_t j;
                for (j = 0; j < subnet->hidden_layer_count && remaining > 100; j++) {
                    written = snprintf(content + pos, remaining,
                        "/* Hidden layer %zu: %zu nodes */\n",
                        (size_t)j, (size_t)subnet->hidden_layer_sizes[j]);
                    pos += written;
                    remaining -= written;
                }
            }
        }
    }

    written = snprintf(content + pos, remaining,
        "\nvoid* network_init_create(void) {\n"
        "    return NULL;\n"
        "}\n\n"
        "void network_init_destroy(void* ctx) {\n"
        "    (void)ctx;\n"
        "}\n\n"
        "int network_init_weights(void* ctx, void* network_ctx) {\n"
        "    (void)ctx;\n"
        "    (void)network_ctx;\n"
        "    return 0;\n"
        "}\n");

    st = prof_path_ensure_parent_directory(layout->network_init.c_path);
    if (st != PROF_STATUS_OK) {
        return prof_error_set(ctx->error, st,
            "Failed to create directory for network_init.c");
    }

    st = write_file(layout->network_init.c_path, content);
    if (st != PROF_STATUS_OK) {
        return prof_error_set(ctx->error, st,
            "Failed to write network_init.c");
    }

    if (layout->network_init.h_path != NULL) {
        const char* header_content =
            "/* network_init.h - Network initialization interface */\n"
            "/* Auto-generated by profiler */\n\n"
            "#ifndef NETWORK_INIT_H\n"
            "#define NETWORK_INIT_H\n\n"
            "#include <stddef.h>\n\n"
            "void* network_init_create(void);\n"
            "void network_init_destroy(void* ctx);\n"
            "int network_init_weights(void* ctx, void* network_ctx);\n\n"
            "#endif\n";

        st = prof_path_ensure_parent_directory(layout->network_init.h_path);
        if (st == PROF_STATUS_OK) {
            write_file(layout->network_init.h_path, header_content);
        }
    }

    return PROF_STATUS_OK;
}

ProfStatus prof_codegen_weights_load(ProfCodegenContext* ctx) {
    ProfStatus st;
    const ProfOutputLayout* layout;
    const NN_NetworkDef* network;
    NNSubnetDef* subnet;
    char content[4096];

    if (ctx == NULL) {
        return PROF_STATUS_INVALID_ARGUMENT;
    }

    layout = ctx->output_layout;
    network = ctx->network;
    subnet = (network != NULL && network->subnet_count > 0U) ? network->subnets[0] : NULL;

    if (layout == NULL || layout->weights_load.c_path == NULL) {
        return PROF_STATUS_PATH_INVALID;
    }

    snprintf(content, sizeof(content),
        "/* weights_load.c - Weights loading module */\n"
        "/* Auto-generated by profiler */\n\n"
        "#include \"weights_load.h\"\n"
        "#include \"infer.h\"\n"
        "#include \"network_metadata.h\"\n"
        "#include \"nn/nn_infer_registry.h\"\n"
        "#include <stdio.h>\n"
        "#include <stdint.h>\n"
        "#include <string.h>\n\n"
        "/* Expected network hash - generated from network definition */\n"
        "static const uint64_t EXPECTED_HASH = 0x%016llxULL;\n"
        "static const uint64_t EXPECTED_LAYOUT_HASH = 0x%016llxULL;\n\n"
        "typedef struct {\n"
        "    uint64_t network_hash;\n"
        "    uint64_t layout_hash;\n"
        "    uint32_t abi_version;\n"
        "} WeightFileHeader;\n\n"
        "static int weights_validate_header(FILE* fp) {\n"
        "    WeightFileHeader header;\n\n"
        "    if (fp == NULL) return -3;\n\n"
        "    if (fread(&header, sizeof(header), 1, fp) != 1) {\n"
        "        return -3;\n"
        "    }\n\n"
        "    if (header.network_hash != EXPECTED_HASH) {\n"
        "        return -4;\n"
        "    }\n\n"
        "    if (header.layout_hash != EXPECTED_LAYOUT_HASH) {\n"
        "        return -5;\n"
        "    }\n\n"
        "    if (header.abi_version != ABI_VERSION) {\n"
        "        return -6;\n"
        "    }\n\n"
        "    return 0;\n"
        "}\n\n"
        "int weights_load_from_file(void* infer_ctx, const char* file_path) {\n"
        "    FILE* fp;\n"
        "    const NNInferRegistryEntry* entry;\n"
        "    void* native_infer_ctx;\n"
        "    int rc;\n\n"
        "    if (file_path == NULL) return -1;\n\n"
        "    fp = fopen(file_path, \"rb\");\n"
        "    if (fp == NULL) return -2;\n\n"
        "    rc = weights_validate_header(fp);\n"
        "    if (rc != 0) {\n"
        "        fclose(fp);\n"
        "        return rc;\n"
        "    }\n\n"
        "    if (infer_ctx == NULL) {\n"
        "        fclose(fp);\n"
        "        return 0;\n"
        "    }\n\n"
        "    if (fseek(fp, 0L, SEEK_SET) != 0) {\n"
        "        fclose(fp);\n"
        "        return -7;\n"
        "    }\n\n"
        "    native_infer_ctx = infer_get_native_context(infer_ctx);\n"
        "    if (native_infer_ctx == NULL) {\n"
        "        fclose(fp);\n"
        "        return -8;\n"
        "    }\n\n"
        "    if (nn_infer_registry_bootstrap() != 0) {\n"
        "        fclose(fp);\n"
        "        return -9;\n"
        "    }\n\n"
        "    entry = nn_infer_registry_find_entry(\"%s\");\n"
        "    if (entry == NULL || entry->load_weights == NULL) {\n"
        "        fclose(fp);\n"
        "        return -10;\n"
        "    }\n\n"
        "    if (entry->load_weights(native_infer_ctx, fp) == 0) {\n"
        "        fclose(fp);\n"
        "        return -11;\n"
        "    }\n\n"
        "    fclose(fp);\n"
        "    return 0;\n"
        "}\n\n"
        "int weights_load_validate(const char* file_path) {\n"
        "    return weights_load_from_file(NULL, file_path);\n"
        "}\n",
        (unsigned long long)ctx->network_hash,
        (unsigned long long)ctx->layout_hash,
        subnet != NULL ? subnet->subnet_type : "unknown");

    st = prof_path_ensure_parent_directory(layout->weights_load.c_path);
    if (st != PROF_STATUS_OK) {
        return prof_error_set(ctx->error, st,
            "Failed to create directory for weights_load.c");
    }

    st = write_file(layout->weights_load.c_path, content);
    if (st != PROF_STATUS_OK) {
        return prof_error_set(ctx->error, st,
            "Failed to write weights_load.c");
    }

    if (layout->weights_load.h_path != NULL) {
        const char* header_content =
            "/* weights_load.h - Weights loading interface */\n"
            "/* Auto-generated by profiler */\n\n"
            "#ifndef WEIGHTS_LOAD_H\n"
            "#define WEIGHTS_LOAD_H\n\n"
            "#include <stddef.h>\n"
            "#include <stdint.h>\n\n"
            "int weights_load_from_file(void* ctx, const char* file_path);\n"
            "int weights_load_validate(const char* file_path);\n\n"
            "#endif\n";

        st = prof_path_ensure_parent_directory(layout->weights_load.h_path);
        if (st == PROF_STATUS_OK) {
            write_file(layout->weights_load.h_path, header_content);
        }
    }

    return PROF_STATUS_OK;
}

/**
 * @brief Get the type-specific train include path
 */
ProfStatus prof_codegen_train(ProfCodegenContext* ctx) {
    ProfStatus st;
    const ProfOutputLayout* layout;
    const NN_NetworkDef* network;
    NNSubnetDef* subnet;
    char content[16384];
    size_t pos = 0U;

    if (ctx == NULL) {
        return PROF_STATUS_INVALID_ARGUMENT;
    }

    layout = ctx->output_layout;
    network = ctx->network;

    if (layout == NULL || layout->train.c_path == NULL) {
        return PROF_STATUS_PATH_INVALID;
    }

    subnet = (network != NULL && network->subnet_count > 0U) ? network->subnets[0] : NULL;

    if (append_format(
            content,
            sizeof(content),
            &pos,
            "/* train.c - Training module */\n"
            "/* Auto-generated by profiler */\n"
            "/* Network: %s */\n"
            "/* Network type: %s */\n\n"
            "#include \"train.h\"\n"
            "#include \"infer.h\"\n"
            "#include \"nn/nn_codegen_hooks.h\"\n"
            "#include \"nn/nn_train_registry.h\"\n"
            "#include <stdlib.h>\n"
            "#include <string.h>\n",
            network != NULL ? network->network_name : "unknown",
            subnet != NULL ? subnet->subnet_type : "unknown") != 0) {
        return prof_error_set(ctx->error, PROF_STATUS_INTERNAL_ERROR,
            "Failed to assemble generated train module");
    }

    if (subnet != NULL &&
        subnet->train_config_header_path != NULL &&
        append_format(
            content,
            sizeof(content),
            &pos,
            "#include \"%s\"\n",
            subnet->train_config_header_path) != 0) {
        return prof_error_set(ctx->error, PROF_STATUS_INTERNAL_ERROR,
            "Failed to assemble generated train module include");
    }

    if (append_format(content, sizeof(content), &pos, "\n") != 0) {
        return prof_error_set(ctx->error, PROF_STATUS_INTERNAL_ERROR,
            "Failed to assemble generated train module spacing");
    }

    if (subnet != NULL &&
        subnet->train_type_config_data != NULL &&
        subnet->train_type_config_size > 0U &&
        append_type_config_blob(
            content,
            sizeof(content),
            &pos,
            "g_train_type_config_bytes",
            subnet->train_type_config_data,
            subnet->train_type_config_size) != 0) {
        return prof_error_set(ctx->error, PROF_STATUS_INTERNAL_ERROR,
            "Failed to assemble generated train module config blob");
    }

    if (append_format(
            content,
            sizeof(content),
            &pos,
            "typedef struct {\n"
            "    const NNTrainRegistryEntry* registry_entry;\n"
            "    void* infer_ctx;\n"
            "    void* train_ctx;\n"
            "    NNCodegenTrainConfig config;\n"
            "    int epoch_count;\n"
            "} TrainContext;\n\n") != 0) {
        return prof_error_set(ctx->error, PROF_STATUS_INTERNAL_ERROR,
            "Failed to assemble generated train module context");
    }

    if (append_format(
            content,
            sizeof(content),
            &pos,
            "void* train_create(void* infer_ctx) {\n"
            "    TrainContext* ctx;\n"
            "    void* native_infer_ctx;\n"
            "    if (infer_ctx == NULL) return NULL;\n"
            "    native_infer_ctx = infer_get_native_context(infer_ctx);\n"
            "    if (native_infer_ctx == NULL) return NULL;\n"
            "    if (nn_train_registry_bootstrap() != 0) return NULL;\n"
            "    ctx = (TrainContext*)malloc(sizeof(TrainContext));\n"
            "    if (ctx == NULL) return NULL;\n"
            "    memset(ctx, 0, sizeof(TrainContext));\n"
            "    ctx->registry_entry = nn_train_registry_find_entry(\"%s\");\n"
            "    if (ctx->registry_entry == NULL || ctx->registry_entry->create == NULL ||\n"
            "        ctx->registry_entry->destroy == NULL || ctx->registry_entry->step_with_data == NULL) {\n"
            "        free(ctx);\n"
            "        return NULL;\n"
            "    }\n"
            "    ctx->infer_ctx = native_infer_ctx;\n"
            "    ctx->config.learning_rate = 0.0f;\n"
            "    ctx->config.momentum = 0.0f;\n"
            "    ctx->config.weight_decay = 0.0f;\n"
            "    ctx->config.batch_size = 0U;\n"
            "    ctx->config.seed = 0U;\n"
            "    ctx->config.type_config = NULL;\n"
            "    ctx->config.type_config_size = 0U;\n"
            "    ctx->config.type_config_type_name = NULL;\n",
            subnet != NULL ? subnet->subnet_type : "unknown") != 0) {
        return prof_error_set(ctx->error, PROF_STATUS_INTERNAL_ERROR,
            "Failed to assemble generated train module create");
    }

    if (subnet != NULL &&
        subnet->train_config_type_name != NULL &&
        subnet->train_type_config_data != NULL &&
        subnet->train_type_config_size > 0U) {
        if (append_format(
                content,
                sizeof(content),
                &pos,
                "    {\n"
                "        %s typed_config;\n"
                "        (void)memcpy(&typed_config, g_train_type_config_bytes, sizeof(typed_config));\n"
                "        ctx->config.type_config = &typed_config;\n"
                "        ctx->config.type_config_size = sizeof(typed_config);\n"
                "        ctx->config.type_config_type_name = \"%s\";\n"
                "        ctx->train_ctx = ctx->registry_entry->create(native_infer_ctx, &ctx->config);\n"
                "    }\n",
                subnet->train_config_type_name,
                subnet->train_config_type_name) != 0) {
            return prof_error_set(ctx->error, PROF_STATUS_INTERNAL_ERROR,
                "Failed to assemble generated train typed config");
        }
    } else if (append_format(
                   content,
                   sizeof(content),
                   &pos,
                   "    ctx->train_ctx = ctx->registry_entry->create(native_infer_ctx, &ctx->config);\n") != 0) {
        return prof_error_set(ctx->error, PROF_STATUS_INTERNAL_ERROR,
            "Failed to assemble generated train generic config");
    }

    if (append_format(
            content,
            sizeof(content),
            &pos,
            "    if (ctx->train_ctx == NULL) {\n"
            "        free(ctx);\n"
            "        return NULL;\n"
            "    }\n"
            "    return ctx;\n"
            "}\n\n"
            "void train_destroy(void* ctx) {\n"
            "    TrainContext* tc = (TrainContext*)ctx;\n"
            "    if (tc == NULL) return;\n"
            "    if (tc->registry_entry != NULL && tc->registry_entry->destroy != NULL && tc->train_ctx != NULL) {\n"
            "        tc->registry_entry->destroy(tc->train_ctx);\n"
            "    }\n"
            "    free(tc);\n"
            "}\n\n"
            "int train_step(void* ctx, const void* input, const void* target) {\n"
            "    TrainContext* tc = (TrainContext*)ctx;\n"
            "    if (tc == NULL || tc->registry_entry == NULL || tc->registry_entry->step_with_data == NULL || tc->train_ctx == NULL) return -1;\n"
            "    return tc->registry_entry->step_with_data(tc->train_ctx, input, target);\n"
            "}\n\n"
            "int train_epoch(void* ctx, int epoch) {\n"
            "    TrainContext* tc = (TrainContext*)ctx;\n"
            "    (void)epoch;\n"
            "    if (tc == NULL) return -1;\n"
            "    tc->epoch_count += 1;\n"
            "    return 0;\n"
            "}\n\n"
            "int train_auto_run(void* ctx, int epochs) {\n"
            "    TrainContext* tc = (TrainContext*)ctx;\n"
            "    int e;\n"
            "    if (tc == NULL) return -1;\n"
            "    for (e = 0; e < epochs; ++e) {\n"
            "        if (train_epoch(ctx, e) != 0) return -1;\n"
            "    }\n"
            "    return 0;\n"
            "}\n\n"
            "float train_get_loss(void* ctx) {\n"
            "    size_t epochs = 0U;\n"
            "    size_t steps = 0U;\n"
            "    float avg_loss = 0.0f;\n"
            "    TrainContext* tc = (TrainContext*)ctx;\n"
            "    if (tc == NULL || tc->registry_entry == NULL || tc->train_ctx == NULL) return 0.0f;\n"
            "    if (tc->registry_entry->get_stats != NULL) {\n"
            "        tc->registry_entry->get_stats(tc->train_ctx, &epochs, &steps, &avg_loss);\n"
            "    }\n"
            "    return avg_loss;\n"
            "}\n") != 0) {
        return prof_error_set(ctx->error, PROF_STATUS_INTERNAL_ERROR,
            "Failed to assemble generated train trailing code");
    }

    st = prof_path_ensure_parent_directory(layout->train.c_path);
    if (st != PROF_STATUS_OK) {
        return prof_error_set(ctx->error, st,
            "Failed to create directory for train.c");
    }

    st = write_file(layout->train.c_path, content);
    if (st != PROF_STATUS_OK) {
        return prof_error_set(ctx->error, st,
            "Failed to write train.c");
    }

    if (layout->train.h_path != NULL) {
        const char* header_content =
            "/* train.h - Training interface */\n"
            "/* Auto-generated by profiler */\n"
            "#ifndef TRAIN_H\n"
            "#define TRAIN_H\n\n"
            "void* train_create(void* infer_ctx);\n"
            "void train_destroy(void* ctx);\n"
            "int train_step(void* ctx, const void* input, const void* target);\n"
            "int train_epoch(void* ctx, int epoch);\n"
            "int train_auto_run(void* ctx, int epochs);\n"
            "float train_get_loss(void* ctx);\n\n"
            "#endif\n";

        st = prof_path_ensure_parent_directory(layout->train.h_path);
        if (st == PROF_STATUS_OK) {
            write_file(layout->train.h_path, header_content);
        }
    }

    return PROF_STATUS_OK;
}

ProfStatus prof_codegen_weights_save(ProfCodegenContext* ctx) {
    ProfStatus st;
    const ProfOutputLayout* layout;
    const NN_NetworkDef* network;
    NNSubnetDef* subnet;
    char content[4096];

    if (ctx == NULL) {
        return PROF_STATUS_INVALID_ARGUMENT;
    }

    layout = ctx->output_layout;
    network = ctx->network;
    subnet = (network != NULL && network->subnet_count > 0U) ? network->subnets[0] : NULL;

    if (layout == NULL || layout->weights_save.c_path == NULL) {
        return PROF_STATUS_PATH_INVALID;
    }

    snprintf(content, sizeof(content),
        "/* weights_save.c - Weights saving module */\n"
        "/* Auto-generated by profiler */\n\n"
        "#include \"weights_save.h\"\n"
        "#include \"infer.h\"\n"
        "#include \"nn/nn_infer_registry.h\"\n"
        "#include <stdio.h>\n"
        "int weights_save_to_file(void* infer_ctx, const char* file_path) {\n"
        "    FILE* fp;\n"
        "    const NNInferRegistryEntry* entry;\n"
        "    void* native_infer_ctx;\n\n"
        "    if (infer_ctx == NULL || file_path == NULL) return -1;\n\n"
        "    native_infer_ctx = infer_get_native_context(infer_ctx);\n"
        "    if (native_infer_ctx == NULL) return -2;\n\n"
        "    if (nn_infer_registry_bootstrap() != 0) return -3;\n\n"
        "    entry = nn_infer_registry_find_entry(\"%s\");\n"
        "    if (entry == NULL || entry->save_weights == NULL) return -4;\n\n"
        "    fp = fopen(file_path, \"wb\");\n"
        "    if (fp == NULL) return -5;\n\n"
        "    if (entry->save_weights(native_infer_ctx, fp) == 0) {\n"
        "        fclose(fp);\n"
        "        return -6;\n"
        "    }\n\n"
        "    fclose(fp);\n"
        "    return 0;\n"
        "}\n",
        subnet != NULL ? subnet->subnet_type : "unknown");

    st = prof_path_ensure_parent_directory(layout->weights_save.c_path);
    if (st != PROF_STATUS_OK) {
        return prof_error_set(ctx->error, st,
            "Failed to create directory for weights_save.c");
    }

    st = write_file(layout->weights_save.c_path, content);
    if (st != PROF_STATUS_OK) {
        return prof_error_set(ctx->error, st,
            "Failed to write weights_save.c");
    }

    if (layout->weights_save.h_path != NULL) {
        const char* header_content =
            "/* weights_save.h - Weights saving interface */\n"
            "/* Auto-generated by profiler */\n\n"
            "#ifndef WEIGHTS_SAVE_H\n"
            "#define WEIGHTS_SAVE_H\n\n"
            "int weights_save_to_file(void* infer_ctx, const char* file_path);\n\n"
            "#endif\n";

        st = prof_path_ensure_parent_directory(layout->weights_save.h_path);
        if (st == PROF_STATUS_OK) {
            write_file(layout->weights_save.h_path, header_content);
        }
    }

    return PROF_STATUS_OK;
}

/**
 * @brief Get the type-specific include path for network operations
 *
 * Maps network type (mlp, transformer, cnn, rnn) to the corresponding
 * header file path in src/nn/types/.
 */
ProfStatus prof_codegen_infer(ProfCodegenContext* ctx) {
    ProfStatus st;
    const ProfOutputLayout* layout;
    const NN_NetworkDef* network;
    NNSubnetDef* subnet;
    char content[16384];
    size_t pos = 0U;
    size_t i = 0U;

    if (ctx == NULL) {
        return PROF_STATUS_INVALID_ARGUMENT;
    }

    layout = ctx->output_layout;
    network = ctx->network;

    if (layout == NULL || layout->infer.c_path == NULL) {
        return PROF_STATUS_PATH_INVALID;
    }

    subnet = (network != NULL && network->subnet_count > 0U) ? network->subnets[0] : NULL;

    if (append_format(
            content,
            sizeof(content),
            &pos,
            "/* infer.c - Inference module */\n"
            "/* Auto-generated by profiler */\n"
            "/* Network: %s */\n"
            "/* Network type: %s */\n\n"
            "#include \"infer.h\"\n"
            "#include \"nn/nn_codegen_hooks.h\"\n"
            "#include \"nn/nn_infer_registry.h\"\n"
            "#include <stdlib.h>\n"
            "#include <string.h>\n",
            network != NULL ? network->network_name : "unknown",
            subnet != NULL ? subnet->subnet_type : "unknown") != 0) {
        return prof_error_set(ctx->error, PROF_STATUS_INTERNAL_ERROR,
            "Failed to assemble generated infer module");
    }

    if (subnet != NULL &&
        subnet->infer_config_header_path != NULL &&
        append_format(
            content,
            sizeof(content),
            &pos,
            "#include \"%s\"\n",
            subnet->infer_config_header_path) != 0) {
        return prof_error_set(ctx->error, PROF_STATUS_INTERNAL_ERROR,
            "Failed to assemble generated infer module include");
    }

    if (append_format(content, sizeof(content), &pos, "\n") != 0) {
        return prof_error_set(ctx->error, PROF_STATUS_INTERNAL_ERROR,
            "Failed to assemble generated infer module spacing");
    }

    if (subnet != NULL &&
        subnet->infer_type_config_data != NULL &&
        subnet->infer_type_config_size > 0U &&
        append_type_config_blob(
            content,
            sizeof(content),
            &pos,
            "g_infer_type_config_bytes",
            subnet->infer_type_config_data,
            subnet->infer_type_config_size) != 0) {
        return prof_error_set(ctx->error, PROF_STATUS_INTERNAL_ERROR,
            "Failed to assemble generated infer module config blob");
    }

    if (append_format(
            content,
            sizeof(content),
            &pos,
            "typedef struct {\n"
            "    const NNInferRegistryEntry* registry_entry;\n"
            "    void* network_ctx;\n"
            "    NNCodegenInferConfig config;\n"
            "} InferContext;\n\n") != 0) {
        return prof_error_set(ctx->error, PROF_STATUS_INTERNAL_ERROR,
            "Failed to assemble generated infer module context");
    }

    if (append_format(
            content,
            sizeof(content),
            &pos,
            "void* infer_create(void) {\n"
            "    InferContext* ctx;\n"
            "    if (nn_infer_registry_bootstrap() != 0) return NULL;\n"
            "    ctx = (InferContext*)malloc(sizeof(InferContext));\n"
            "    if (ctx == NULL) return NULL;\n"
            "    memset(ctx, 0, sizeof(InferContext));\n"
            "    ctx->registry_entry = nn_infer_registry_find_entry(\"%s\");\n"
            "    if (ctx->registry_entry == NULL || ctx->registry_entry->create == NULL ||\n"
            "        ctx->registry_entry->destroy == NULL || ctx->registry_entry->auto_run == NULL) {\n"
            "        free(ctx);\n"
            "        return NULL;\n"
            "    }\n"
            "    ctx->config.network_type = \"%s\";\n"
            "    ctx->config.input_size = %zu;\n"
            "    ctx->config.hidden_layer_count = %zu;\n"
            "    ctx->config.output_size = %zu;\n"
            "    ctx->config.network_hash = 0x%016llxULL;\n"
            "    ctx->config.layout_hash = 0x%016llxULL;\n"
            "    ctx->config.seed = 0U;\n"
            "    ctx->config.type_config = NULL;\n"
            "    ctx->config.type_config_size = 0U;\n"
            "    ctx->config.type_config_type_name = NULL;\n",
            subnet != NULL ? subnet->subnet_type : "unknown",
            subnet != NULL ? subnet->subnet_type : "unknown",
            subnet != NULL ? (size_t)subnet->input_layer_size : (size_t)0U,
            subnet != NULL ? (size_t)subnet->hidden_layer_count : (size_t)0U,
            subnet != NULL ? (size_t)subnet->output_layer_size : (size_t)0U,
            (unsigned long long)ctx->network_hash,
            (unsigned long long)ctx->layout_hash) != 0) {
        return prof_error_set(ctx->error, PROF_STATUS_INTERNAL_ERROR,
            "Failed to assemble generated infer create");
    }

    if (subnet != NULL && subnet->hidden_layer_sizes != NULL) {
        size_t hidden_count = subnet->hidden_layer_count;
        if (hidden_count > 4U) {
            hidden_count = 4U;
        }
        for (i = 0U; i < hidden_count; ++i) {
            if (append_format(
                    content,
                    sizeof(content),
                    &pos,
                    "    ctx->config.hidden_sizes[%zu] = %zu;\n",
                    i,
                    (size_t)subnet->hidden_layer_sizes[i]) != 0) {
                return prof_error_set(ctx->error, PROF_STATUS_INTERNAL_ERROR,
                    "Failed to assemble generated infer hidden layer config");
            }
        }
    }
    for (; i < 4U; ++i) {
        if (append_format(
                content,
                sizeof(content),
                &pos,
                "    ctx->config.hidden_sizes[%zu] = 0U;\n",
                i) != 0) {
            return prof_error_set(ctx->error, PROF_STATUS_INTERNAL_ERROR,
                "Failed to assemble generated infer hidden layer padding");
        }
    }

    if (subnet != NULL &&
        subnet->infer_config_type_name != NULL &&
        subnet->infer_type_config_data != NULL &&
        subnet->infer_type_config_size > 0U) {
        if (append_format(
                content,
                sizeof(content),
                &pos,
                "    {\n"
                "        %s typed_config;\n"
                "        (void)memcpy(&typed_config, g_infer_type_config_bytes, sizeof(typed_config));\n"
                "        ctx->config.type_config = &typed_config;\n"
                "        ctx->config.type_config_size = sizeof(typed_config);\n"
                "        ctx->config.type_config_type_name = \"%s\";\n"
                "        ctx->network_ctx = ctx->registry_entry->create(&ctx->config);\n"
                "    }\n",
                subnet->infer_config_type_name,
                subnet->infer_config_type_name) != 0) {
            return prof_error_set(ctx->error, PROF_STATUS_INTERNAL_ERROR,
                "Failed to assemble generated infer typed config");
        }
    } else if (append_format(
                   content,
                   sizeof(content),
                   &pos,
                   "    ctx->network_ctx = ctx->registry_entry->create(&ctx->config);\n") != 0) {
        return prof_error_set(ctx->error, PROF_STATUS_INTERNAL_ERROR,
            "Failed to assemble generated infer generic config");
    }

    if (append_format(
            content,
            sizeof(content),
            &pos,
            "    if (ctx->network_ctx == NULL) {\n"
            "        free(ctx);\n"
            "        return NULL;\n"
            "    }\n"
            "    return ctx;\n"
            "}\n\n"
            "void infer_destroy(void* ctx) {\n"
            "    InferContext* ic = (InferContext*)ctx;\n"
            "    if (ic == NULL) return;\n"
            "    if (ic->registry_entry != NULL && ic->registry_entry->destroy != NULL && ic->network_ctx != NULL) {\n"
            "        ic->registry_entry->destroy(ic->network_ctx);\n"
            "    }\n"
            "    free(ic);\n"
            "}\n\n"
            "void* infer_get_native_context(void* ctx) {\n"
            "    InferContext* ic = (InferContext*)ctx;\n"
            "    if (ic == NULL) return NULL;\n"
            "    return ic->network_ctx;\n"
            "}\n\n"
            "int infer_step(void* ctx, const void* input, void* output) {\n"
            "    InferContext* ic = (InferContext*)ctx;\n"
            "    (void)input;\n"
            "    (void)output;\n"
            "    if (ic == NULL || ic->registry_entry == NULL || ic->registry_entry->infer_step == NULL || ic->network_ctx == NULL) return -1;\n"
            "    return ic->registry_entry->infer_step(ic->network_ctx);\n"
            "}\n\n"
            "int infer_auto_run(void* ctx, const void* input, void* output) {\n"
            "    InferContext* ic = (InferContext*)ctx;\n"
            "    if (ic == NULL || ic->registry_entry == NULL || ic->registry_entry->auto_run == NULL || ic->network_ctx == NULL) return -1;\n"
            "    return ic->registry_entry->auto_run(ic->network_ctx, input, output);\n"
            "}\n") != 0) {
        return prof_error_set(ctx->error, PROF_STATUS_INTERNAL_ERROR,
            "Failed to assemble generated infer trailing code");
    }

    st = prof_path_ensure_parent_directory(layout->infer.c_path);
    if (st != PROF_STATUS_OK) {
        return prof_error_set(ctx->error, st,
            "Failed to create directory for infer.c");
    }

    st = write_file(layout->infer.c_path, content);
    if (st != PROF_STATUS_OK) {
        return prof_error_set(ctx->error, st,
            "Failed to write infer.c");
    }

    if (layout->infer.h_path != NULL) {
        const char* header_content =
            "/* infer.h - Inference interface */\n"
            "/* Auto-generated by profiler */\n"
            "#ifndef INFER_H\n"
            "#define INFER_H\n\n"
            "void* infer_create(void);\n"
            "void infer_destroy(void* ctx);\n"
            "void* infer_get_native_context(void* ctx);\n"
            "int infer_step(void* ctx, const void* input, void* output);\n"
            "int infer_auto_run(void* ctx, const void* input, void* output);\n\n"
            "#endif\n";

        st = prof_path_ensure_parent_directory(layout->infer.h_path);
        if (st == PROF_STATUS_OK) {
            write_file(layout->infer.h_path, header_content);
        }
    }

    return PROF_STATUS_OK;
}

ProfStatus prof_codegen_generate_all(ProfCodegenContext* ctx) {
    ProfStatus st;

    if (ctx == NULL || ctx->network == NULL) {
        return PROF_STATUS_INVALID_ARGUMENT;
    }

    st = prof_codegen_metadata(ctx, ctx->output_layout->metadata_path);
    if (st != PROF_STATUS_OK) return st;

    st = prof_codegen_tokenizer(ctx);
    if (st != PROF_STATUS_OK) return st;

    st = prof_codegen_network_init(ctx);
    if (st != PROF_STATUS_OK) return st;

    st = prof_codegen_weights_load(ctx);
    if (st != PROF_STATUS_OK) return st;

    st = prof_codegen_train(ctx);
    if (st != PROF_STATUS_OK) return st;

    st = prof_codegen_weights_save(ctx);
    if (st != PROF_STATUS_OK) return st;

    st = prof_codegen_infer(ctx);
    if (st != PROF_STATUS_OK) return st;

    return PROF_STATUS_OK;
}
