/* Auto-generated by profiler.c. DO NOT EDIT. */
#ifndef NETWORK_DEF_H
#define NETWORK_DEF_H

#include "config_user.h"

/* 资源估算结果：单位为 float 元素数 */
#define NETWORK_TOTAL_PARAMS      207940U
#define NETWORK_PEAK_ACTIVATION   4096U
#define NETWORK_EST_FLOPS         13108736U
#define NETWORK_PARAM_BYTES       (NETWORK_TOTAL_PARAMS * sizeof(float))
#define NETWORK_ACT_BYTES         (NETWORK_PEAK_ACTIVATION * sizeof(float))
#define STATIC_POOL_SIZE          NETWORK_TOTAL_PARAMS
#define DYNAMIC_POOL_SIZE         NETWORK_PEAK_ACTIVATION
#define EST_FLOPS                 NETWORK_EST_FLOPS

/* IO 映射：0=Sigmoid, 1=Tanh */
#define NETWORK_IO_COUNT          4
static const int NETWORK_IO_ACTIVATIONS[OUTPUT_DIM] = {0, 0, 1, 1};
static const char* const NETWORK_IO_NAMES[OUTPUT_DIM] = {"Key_W", "Key_A", "Mouse_X", "Mouse_Y"};

#endif /* NETWORK_DEF_H */
