#if defined(_WIN32) && !defined(_CRT_SECURE_NO_WARNINGS)
#define _CRT_SECURE_NO_WARNINGS
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../include/config_user.h"

/**
 * @brief 记录单层资源估算结果，便于打印与汇总。
 */
typedef struct LayerProfile {
    const char* name;
    size_t in_size;
    size_t out_size;
    size_t params;
    size_t flops;
    size_t peak_activation;
} LayerProfile;

/**
 * @brief Profiler 上下文，保存全局统计值。
 */
typedef struct ProfilerContext {
    size_t total_params;
    size_t max_activation;
    size_t total_flops;
    size_t current_io_size;
    size_t layer_count;
    LayerProfile layers[64];
} ProfilerContext;

/**
 * @brief 统一保存 IO 映射配置，避免多处重复展开宏。
 */
typedef struct IoMapping {
    int activations[OUTPUT_DIM];
    const char* names[OUTPUT_DIM];
} IoMapping;

/**
 * @brief 记录一层资源消耗并更新上下文累计值。
 *
 * 设计约束：
 * - 单线程、静态估算，不依赖运行时输入数据。
 * - 激活内存采用双缓冲近似：输入缓冲 + 输出缓冲。
 *
 * @param ctx           Profiler 上下文
 * @param layer_name    层名称
 * @param in_size       输入元素数（float）
 * @param out_size      输出元素数（float）
 * @param params        本层参数量（float）
 * @param flops         本层 FLOPs 估算值
 */
static void profiler_add_layer(ProfilerContext* ctx,
                               const char* layer_name,
                               size_t in_size,
                               size_t out_size,
                               size_t params,
                               size_t flops) {
    size_t peak_for_layer = ctx->current_io_size + out_size;
    LayerProfile* layer = NULL;

    ctx->total_params += params;
    ctx->total_flops += flops;
    if (peak_for_layer > ctx->max_activation) {
        ctx->max_activation = peak_for_layer;
    }

    if (ctx->layer_count < (sizeof(ctx->layers) / sizeof(ctx->layers[0]))) {
        layer = &ctx->layers[ctx->layer_count++];
        layer->name = layer_name;
        layer->in_size = in_size;
        layer->out_size = out_size;
        layer->params = params;
        layer->flops = flops;
        layer->peak_activation = peak_for_layer;
    }

    ctx->current_io_size = out_size;
}

/**
 * @brief 打印分层报告，便于校验网络规模估算是否符合预期。
 *
 * @param ctx Profiler 上下文
 */
static void profiler_print_layer_table(const ProfilerContext* ctx) {
    size_t i = 0U;
    printf("---------------------------------------------------------------\n");
    printf("%-18s %-10s %-10s %-12s %-12s\n", "Layer", "In", "Out", "Params", "FLOPs");
    printf("---------------------------------------------------------------\n");
    for (i = 0U; i < ctx->layer_count; ++i) {
        const LayerProfile* l = &ctx->layers[i];
        printf("%-18s %-10zu %-10zu %-12zu %-12zu\n",
               l->name, l->in_size, l->out_size, l->params, l->flops);
    }
    printf("---------------------------------------------------------------\n");
}

/**
 * @brief 打印 IO 映射报告，显示每个输出通道的激活函数与语义。
 *
 * @param io IO 映射配置
 */
static void profiler_print_io_mapping(const IoMapping* io) {
    size_t i = 0U;
    printf("IO Mapping:\n");
    for (i = 0U; i < OUTPUT_DIM; ++i) {
        const char* act_name = (io->activations[i] == 0) ? "Sigmoid" : "Tanh";
        printf("  Out[%zu] %-12s Activation=%s(%d)\n",
               i, io->names[i], act_name, io->activations[i]);
    }
}

/**
 * @brief 生成 network_def.h，供后续编译阶段统一引用。
 *
 * 关键保护点：
 * - 输出头文件中保留 config_user.h 引用，确保用户配置是单一事实来源。
 * - 将 profiler 结果固化为宏，避免运行时重复计算。
 *
 * @param output_path 输出头文件路径
 * @param ctx         Profiler 上下文
 * @param io          IO 映射配置
 * @return int        0 成功，非 0 失败
 */
static int generate_network_def(const char* output_path,
                                const ProfilerContext* ctx,
                                const IoMapping* io) {
    FILE* f = fopen(output_path, "w");
    size_t i = 0U;
    if (f == NULL) {
        perror("Failed to open output file");
        return 1;
    }

    fprintf(f, "/* Auto-generated by profiler.c. DO NOT EDIT. */\n");
    fprintf(f, "#ifndef NETWORK_DEF_H\n");
    fprintf(f, "#define NETWORK_DEF_H\n\n");
    fprintf(f, "#include \"config_user.h\"\n\n");

    fprintf(f, "/* 资源估算结果：单位为 float 元素数 */\n");
    fprintf(f, "#define NETWORK_TOTAL_PARAMS      %zuU\n", ctx->total_params);
    fprintf(f, "#define NETWORK_PEAK_ACTIVATION   %zuU\n", ctx->max_activation);
    fprintf(f, "#define NETWORK_EST_FLOPS         %zuU\n", ctx->total_flops);
    fprintf(f, "#define NETWORK_PARAM_BYTES       (NETWORK_TOTAL_PARAMS * sizeof(float))\n");
    fprintf(f, "#define NETWORK_ACT_BYTES         (NETWORK_PEAK_ACTIVATION * sizeof(float))\n");
    fprintf(f, "#define STATIC_POOL_SIZE          NETWORK_TOTAL_PARAMS\n");
    fprintf(f, "#define DYNAMIC_POOL_SIZE         NETWORK_PEAK_ACTIVATION\n");
    fprintf(f, "#define EST_FLOPS                 NETWORK_EST_FLOPS\n\n");

    fprintf(f, "/* IO 映射：0=Sigmoid, 1=Tanh */\n");
    fprintf(f, "#define NETWORK_IO_COUNT          %d\n", OUTPUT_DIM);
    fprintf(f, "static const int NETWORK_IO_ACTIVATIONS[OUTPUT_DIM] = {");
    for (i = 0U; i < OUTPUT_DIM; ++i) {
        fprintf(f, "%s%d", (i == 0U) ? "" : ", ", io->activations[i]);
    }
    fprintf(f, "};\n");

    fprintf(f, "static const char* const NETWORK_IO_NAMES[OUTPUT_DIM] = {");
    for (i = 0U; i < OUTPUT_DIM; ++i) {
        fprintf(f, "%s\"%s\"", (i == 0U) ? "" : ", ", io->names[i]);
    }
    fprintf(f, "};\n\n");

    fprintf(f, "#endif /* NETWORK_DEF_H */\n");
    fclose(f);
    return 0;
}

/**
 * @brief 根据用户配置执行一次静态资源估算（Dry Run）。
 *
 * @param ctx Profiler 上下文
 */
static void profiler_run(ProfilerContext* ctx) {
    size_t seq_len = (size_t)MAX_SEQ_LEN;
    size_t embed_dim = (size_t)EMBED_DIM;
    size_t ffn_dim = (size_t)FFN_DIM;
    size_t layer_index = 0U;
    size_t embed_out_size = seq_len * embed_dim;

    ctx->current_io_size = seq_len;

    profiler_add_layer(ctx,
                       "Embedding",
                       seq_len,
                       embed_out_size,
                       (size_t)VOCAB_SIZE * embed_dim,
                       0U);

    profiler_add_layer(ctx,
                       "StateProjection",
                       (size_t)STATE_DIM,
                       embed_dim,
                       ((size_t)STATE_DIM * embed_dim) + embed_dim,
                       2U * (size_t)STATE_DIM * embed_dim);

    ctx->current_io_size = embed_out_size;
    for (layer_index = 0U; layer_index < (size_t)NUM_LAYERS; ++layer_index) {
        static const char* names[] = {
            "Encoder_0", "Encoder_1", "Encoder_2", "Encoder_3",
            "Encoder_4", "Encoder_5", "Encoder_6", "Encoder_7"
        };
        const char* layer_name = (layer_index < (sizeof(names) / sizeof(names[0])))
            ? names[layer_index]
            : "Encoder_N";
        size_t d = embed_dim;
        size_t l = seq_len;
        size_t attn_params = 4U * ((d * d) + d);
        size_t attn_flops = (3U * 2U * l * d * d) + (2U * l * l * d) + (2U * l * d * d);
        size_t ffn_params = ((d * ffn_dim) + ffn_dim) + ((ffn_dim * d) + d);
        size_t ffn_flops = (2U * l * d * ffn_dim) + (2U * l * ffn_dim * d);

        profiler_add_layer(ctx,
                           layer_name,
                           embed_out_size,
                           embed_out_size,
                           attn_params + ffn_params,
                           attn_flops + ffn_flops);
    }

    profiler_add_layer(ctx,
                       "ActionHead",
                       embed_out_size,
                       (size_t)OUTPUT_DIM,
                       (embed_dim * (size_t)OUTPUT_DIM) + (size_t)OUTPUT_DIM,
                       2U * embed_dim * (size_t)OUTPUT_DIM);
}

/**
 * @brief 程序入口，执行 profiler 并输出 network_def.h。
 *
 * 用法：
 * - 默认输出：src/include/network_def.h
 * - 自定义输出：profiler -o <output_path>
 *
 * @param argc 参数数量
 * @param argv 参数数组
 * @return int 退出码，0 表示成功
 */
int main(int argc, char** argv) {
    const int io_activations[OUTPUT_DIM] = IO_MAPPING_ACTIVATIONS;
    const char* io_names[OUTPUT_DIM] = IO_MAPPING_NAMES;
    IoMapping io = { {0}, {0} };
    ProfilerContext ctx;
    const char* output_path = "src/include/network_def.h";
    size_t i = 0U;
    int rc = 0;

    memset(&ctx, 0, sizeof(ctx));

    if (argc == 3 && strcmp(argv[1], "-o") == 0) {
        output_path = argv[2];
    } else if (argc != 1) {
        fprintf(stderr, "Usage: %s [-o output_path]\n", argv[0]);
        return 2;
    }

    for (i = 0U; i < OUTPUT_DIM; ++i) {
        io.activations[i] = io_activations[i];
        io.names[i] = io_names[i];
    }

    printf("==================================================\n");
    printf("               C99 Network Profiler               \n");
    printf("==================================================\n");

    profiler_run(&ctx);
    profiler_print_layer_table(&ctx);
    profiler_print_io_mapping(&io);

    printf("Total Parameters : %zu (%.2f KB)\n",
           ctx.total_params, (ctx.total_params * sizeof(float)) / 1024.0);
    printf("Peak Activation  : %zu (%.2f KB)\n",
           ctx.max_activation, (ctx.max_activation * sizeof(float)) / 1024.0);
    printf("Total FLOPs      : %zu (%.2f MFLOPs)\n",
           ctx.total_flops, ctx.total_flops / 1000000.0);
    printf("Output Header    : %s\n", output_path);

    rc = generate_network_def(output_path, &ctx, &io);
    if (rc != 0) {
        return rc;
    }

    printf("Profiler completed successfully.\n");
    return 0;
}
